### PR TITLE
UI: Use Qt api for translation.

### PR DESCRIPTION
**Pull request by wt**
I flushed out the OBSTranslation implementation of QTranslation by
refactoring some logic from OBSApp into OBSTranslation. I then plumbed
QStrings into more places and use the Qt's tr() for translation instead
of the homegrown Str()/QTStr().

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by wt** [comment]
I just rebased this against master as there was a conflicting change.

**Comment by jp9000** [comment]
I'm really terribly sorry about this, but I just can't justify merging it.  I really don't think it's necessary.  I know things aren't ideal, but I just can't really justify it at this point.  There's no real reason why it needs to be one way or the other.  I know you put some effort in to this -- please don't take it the wrong way.

**Comment by wt** [comment]
I am certainly not offended by the decision.

However, I will say that one of the reasons I did it is that QT has a number of translations built in for normal UI components. I did think it would be useful to find a way to use them. That was on my further work list if this was accepted.

**Pull request closed without merging**
