### PR TITLE
only write scenes.json when contents has changed

### PR DESCRIPTION
**Pull request by chhe**
Right now the `scenes.json` is written to disc every 20 (or so) seconds. Regardless of whether the content has changed or not. Since I'm syncing my settings with `ownCloud` I get a lot of needless sync operations.

I reported this already on Mantis (https://obsproject.com/mantis/view.php?id=207).

This behavior was bothering me quite a lot, so I made this PR.

In this PR I changed `OBSBasic::Save()` to only save files if the content would change (by reading the file and comparing both strings). Please keep in mind that I have no recent experience with C or C++ development, so my changes might break stuff. Although I have been running a self-compiled version of `obs-studio ` with this change for about a week now without any problems.

If this PR breaks stuff or is not up to (your) established C/C++ coding standards please consider adding this behavior yourself or tell me what needs to be changed so the PR will be accepted.

Thank You!

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by PsiLupan** [comment]
My only thought is that the 'bool shouldWrite' is unnecessary, given that it's only an extension of the if statement.

**Comment by chhe** [comment]
You are absolutely correct. The bool is unnecessary so I removed it. I'm not sure why it was there in the first place ;-)

**Comment by nopjmp** [comment]
Read the json from the file system can cause unnecessary reads which can spin up hard drives if the json file is outside of the filesystem cache. It would be a better idea to have a 'dirty' flag after a scene is updated and check that instead.

**Comment by jp9000** [comment]
Instead of comparing the string it should really just update when there's an actual change.  I'll see about fixing this problem, though I don't agree with string comparison.  I might end up replacing the code with another fix, if that's okay.

**Comment by chhe** [comment]
I can confirm that with commits 4b93b42dedb13164348e4135d278631d66d63a0f and da358da9a702e18dd73578de01d341d1dbd01d25 `scenes.json` is only written when something has changed. I'll close the pull request. Unfortunately I can't close the Mantis issue I opened (https://obsproject.com/mantis/view.php?id=207).

**Pull request closed without merging**
