### PR TITLE
fix a crash bug.

### PR DESCRIPTION
**Pull request by sorayuki**
how to crash:
1. use recent ffmpeg shared libraries.
2. add a ffmpeg_source, a small static picture (e.g. jpeg) with loop
3. after a while of high cpu usage, it crashed. Seems reproduced more easily on faster computer

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by bean07** [comment]
Im not know how to open issues but everyone help me pls :'(
I'm streaming in incoming days but i upgraded to ubuntu 16.04 anyone use this os pls help me

**Comment by dodgepong** [comment]
You can post on the forums: https://obsproject.com/forum/list/linux-support.34/

**Comment by Gol-D-Ace** [comment]
Please ask here
https://obsproject.com/forum/list/linux-support.34/

**Comment by jp9000** [comment]
Could you check the latest master and see if you're still getting a crash with the media source?  I'm pretty sure that your fix shouldn't be necessary.

**Comment by seung-woo** [comment]
Could you refresh my memory on the context of the crash?

Seung-Woo

On Apr 19, 2016, at 6:35 PM, Jim <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you check the latest master and see if you're still getting a crash with the media source? I'm pretty sure that your fix shouldn't be necessary.

�

**Comment by jp9000** [comment]
Ah, this is for an unrelated pull request related to the media source.  You're probably receiving this message because you're subscribed to the obs-studio repository on github.

**Comment by seung-woo** [comment]
Ok, no homework for me. :)

Seung-Woo

On Apr 19, 2016, at 6:42 PM, Jim <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, this is for an unrelated pull request related to the media source. You're probably receiving this message because you're subscribed to the obs-studio repository on github.

�

**Pull request closed without merging**
