### PR TITLE
mingw-w64 support for obs-studio

### PR DESCRIPTION
**Pull request by martell**
As discussed on irc I will do a PR for mingw-w64 support.
#longliveOSS

This can be merged as is or we can wait until i add the rest of the commits
dx11 support should land tomorrow so its not that long of a wait :)

A review of the changes so far is welcome also

Many Thanks
Martell

### CODE REVIEW

**Comment by martell** [comment]
Okay so now this is at the stage where it can be build on the current mingw-w64.

You will have to disable libobs-d3d11 and win-dshow to get through a complete build.
I have sent a PR to the other project which should fix some issues on the dshow part.

once mingw-w64 4.0 lands I'm confident this should work with a few small changes to libosb-d3d11

Please Review

**Comment by martell** [comment]
Fully complete :)
Test builds sent via irc

**Comment by jp9000** [comment]
Manually merged with some fixes, and also fixed a ton of warnings

**Comment by jp9000** [comment]
Manually merged with some fixes, and also fixed a ton of warnings

**Pull request closed without merging**
