### PR TITLE
Readme: Convert readme to Markdown

### PR DESCRIPTION
**Pull request by viperwarp**
Readme converted to markdown for nicer viewing on Github.

Maintained 80 column limit for vim viewing.

I've added double spaces to newlines to preserve the line breaks that already existed in the old Readme, optionally those could be removed to use standard text wrapping instead.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by viperwarp** [comment]
Removed some extraneous newlines and squashed the commit.

**Comment by jp9000** [comment]
Although I appreciate the gesture, the readme isn't meant to be markdown.  I know that it's prettier and nicer on github and such, but I'd just prefer to leave it as text-only.  I'm terribly sorry for the trouble.

**Comment by viperwarp** [comment]
10 minutes of formatting isn't any trouble, thanks for looking anyway.

**Pull request closed without merging**
