### PR TITLE
Blackmagic DeckLink plugin

### PR DESCRIPTION
**Pull request by SkylerLipthay**
* Mac support only so far
* Only tested with the Blackmagic Intensity Shuttle (USB 3.0) on Mac OS X 10.10.2
* Video format not specifiable (`bmdFormat8BitYUV` support baked in)
* Audio format not specifiable (`bmdAudioSampleRate48kHz`, `bmdAudioSampleType16bitInteger`, 2-channel support baked in)
* Device/mode selection is specifiable

[In action](https://cloud.githubusercontent.com/assets/38674/6205525/eb77b472-b525-11e4-9a65-ccf68c51c844.png)
[Preferences window](https://cloud.githubusercontent.com/assets/38674/6205530/00d9f294-b526-11e4-93a5-d7e1d5cd9089.png)

This is my first time contributing to OBS and my first time using C/C++ in a while, so I'm expecting some obvious issues in here. I'm open to any and all criticism! Overall, I'm not satisfied with the clarity of this code and I'm look for any high-level architectural suggestions.

Notes about interfacing with Blackmagic's SDK:

* Using the latest version: [Desktop Video 10.3.1 SDK (Nov 20 2014)](https://www.blackmagicdesign.com/support)
* The API seems to be the same between platforms besides string manipulation
  * `IDeckLink::GetDisplayName` and `IDeckLinkDisplayMode::GetName` are the two SDK methods currently used that deal with strings
  * `DecklinkStringToStdString` and `decklink_string_t` are platform-specific items to convert into `std::string` (the Mac OS X SDK uses `CFStringRef`)

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by ubuntuaddicted** [comment]
This is awesome! Patiently waiting for Linux implementation. ;)

**Comment by SkylerLipthay** [comment]
I remade the plugin. It's pretty solid now, and conforms well to the repository styles. Still only Mac support for now.

**Comment by SkylerLipthay** [comment]
I've updated this branch with an untested Linux implementation.

**Comment by jp9000** [comment]
ok to test

**Comment by kc5nra** [comment]
ok to test

**Comment by kc5nra** [comment]
test this please

**Comment by kc5nra** [comment]
ok to test

**Comment by kc5nra** [comment]
ok to test

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
test this

**Comment by ubuntuaddicted** [comment]
Just waiting for BlackMagic Design to send me their stuff to benchmark and review in Linux and I'll be helping test this.

**Comment by ckarthikv** [comment]
@SkylerLipthay - Tried this today using the Blackmagic Intensity Shuttle USB 3.0. Audio through HDMI in drops after a few mins into the Livestream. Audio Bitrate was set at 96/ 128 Kbps and sampling rate set at 44.1 Khz. Any ideas?

P.S. - Tried a sampling rate of 22 Khz, and the audio stayed on. 44.1Khz and 48 Khz had an issue.

Pls help.

**Comment by Jack0r** [comment]
Problems and errors are normally reported to the forum to the according section (win/linux/mac) and please include a log file. There is a reason the github issues are not available, so please stop posting to PR's in the future.
https://obsproject.com/forum/categories/obs-multiplatform-support.30/

**Comment by ckarthikv** [comment]
Thanks.

**Pull request merged**
