### PR TITLE
Formatted filename

### PR DESCRIPTION
**Pull request by bl4**
Tracker number 361 Ability to configure output recording filename

This pull request is a feature implementation.

### CODE REVIEW

**Comment by Gol-D-Ace** [comment]
Should have a tool tip explaining all the variables in my opinion. (Like in OBS1.)
Also maybe this should be usable in Simple Output Mode.

**Comment by bl4** [comment]
ToolTip added.

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by chinhseoul** [comment]
theo bạn nó có tác dụng gì?

**Comment by jp9000** [comment]
Thank you very much for this!  I had to delay reviewing/merging this because I wanted to spend a little time tinkering with it for the following features:

1.) I moved the option to advanced settings so it applies to all file names for the program
2.) I added an "overwrite if file exists" option if the user really wants to do that (has happened)
3.) In the case where "overwrite if file exists" is off, and a generic name with no unique time/date format is used, it'll now try to find a unique filename.  For example, if they make the file name format "My Filename", and then the file "My Filename.mp4" already exists, it'll use "My Filename (2).mp4" instead.

I also squashed the last 5 commits together because there wasn't any reason to have them separate.

**Comment by bl4** [comment]
Your'e welcome!  Thank you for the feedback!

**Pull request closed without merging**
