### PR TITLE
Allow OBS_VERSION to be set to assist in packaging.

### PR DESCRIPTION
**Pull request by boombatower**
I am not all that familiar with cmake and as such there may be a better way to do this. When building distro package it would be nice to be able to set the version string which is known in `.spec` file even though there is no `.git` directory. Storing all the git metadata just for setting to visible version number is less than optimal.

_side topic:_
Just to make it clear the openSUSE package in packman repo is the correct location since ffmpeg must be compiled against and is only contained in packman repository for legal reasons. It is officially suggested to use packman for codecs and such. I had discussed with packaging folks and told that packman was best place for obs-studio. As such, it will never be placed in main openSUSE repositories and could be considered _official_. Up to you all, but I am referring to `INSTALL` https://github.com/jp9000/obs-studio/blob/master/INSTALL#L121. I am happy to make a pull request for that. ;)

### CODE REVIEW

**Comment by jp9000** [comment]
We use the version string in many places.  What you're doing right now is making OBS_VERSION basically empty unless explicitly set by the person using cmake.  What you should be doing is making a way to optionally override the variable instead.  Make it do that, and I won't mind merging it.

**Comment by boombatower** [comment]
That was definitely my intent, but I take it `option()` doesn't just make an optional variable with a default.

```
option(OBS_VERSION "OBS version string" ${OBS_VERSION_DEFAULT})
```

I saw that used to UNIX_STRUCTURE which I believe behaves the same way.

**Comment by jp9000** [comment]
I cannot merge it because by default it now sets OBS_VERSION to the string "OFF" instead of its proper version.  So anything that queries the version string now just gets the string "OFF" instead of "0.7.3" for example.

**Comment by boombatower** [comment]
As I said I am not all the familiar with cmake so the issue was with knowing how to implement it, not disagreement on how it should work. I tested the following locally and it seems to behave as expected.

Additionally, I handled the case where `.git` directory is present, but `git` executable is not or fails to provide a version via `describe`.

Now simply set `-DOBS_VERSION="1.2.3"` when building.

**Comment by jp9000** [comment]
Okay, I apologize if I misunderstood; would using a separate variable to set the okay for you?  I can just change it so it operates that way.

**Comment by boombatower** [comment]
Sure

**Comment by jp9000** [comment]
Manually merged here:  https://github.com/jp9000/obs-studio/commit/6158a7418ed3f8b8cdfbb3cce8ec680e3ee5d9c8

Changed it so that it operates via an OBS_VERSION_OVERRIDE variable instead of using the OBS_VERSION variable directly.  If that variable is set, it will use the string it is set to as the version.  If the variable is not set, it will just use the original cmake defaults.

**Comment by jp9000** [comment]
I probably should have showed you those changes on a separate branch before modifying and merging; apologies for that.  Could you confirm that the changes I added will work okay for what you need to do?

**Comment by boombatower** [comment]
https://pmbs.links2linux.de/request/show/1616

merged in update to 0.8.2 and change to _override variable.

**Comment by boombatower** [comment]
Thanks for merging. Question: Is there a reason you didn't keep the change to allow fallback when `.git` directory is present without `git` executable?

**Comment by jp9000** [comment]
I actually should have had you counter-review it, I didn't do that intentionally.  Apologies about that.

**Pull request closed without merging**
