### PR TITLE
frontend-tools: Add output timers

### PR DESCRIPTION
**Pull request by cg2121**
This adds streaming and recording timers to the frontend tools. I have not figured out yet how to make the window modeless.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by cg2121** [comment]
I have now finally got the window to be modeless. Only thing now is to get the frontend events to work.

**Comment by cg2121** [comment]
I have got the frontend events to work now.

**Comment by jp9000** [comment]
Alright, finally had time to spend on this, sorry about the delay (but then again I'm always delayed).

Made a few minor changes:
- Reduced repeated code (particularly in frontend-tools.c)
- Reduced repeated cmake code in the frontend-tools CMakeLists.txt
- Separated that API fix to a different commit (although it was used by the commit, it isn't related to the commit, so that sort of thing should always be separated)
- There was a tiny little bit of trailing whitespace, just a space, keep an eye out for that, it can sneak up on anyone.  I recommend doing a git diff on changes because git will always point out whitespace problems.  If needed, you can also make git remove whitespace problems automatically with "--whitespace=fix" when rebasing.

**Pull request closed without merging**
