### PR TITLE
UI: Add option to disable docking volume

### PR DESCRIPTION
**Pull request by mntone**
System do not reduce OBS Studio volume when use communication app.

### CODE REVIEW

**Comment by WizardCM** [comment]
The term is "ducking". I do like the idea of having this as a setting, but I don't know if people would understand what the option means at first glance, as OBS has no native ducking functionality. Windows has this as a configurable option in Sound -> Communications. Would the two conflict?

**Comment by mntone** [comment]
Two option do not completely match. This option turn off reducing OBS monitoring volume only.

"Disable reducing OBS volume when VoIP" is better? If you have better message, please tell me. I’m sorry, my poor English.

**Comment by mrasmus** [comment]
As mentioned in IRC, I tested this behavior on Windows 10 and confirmed it works. I would suggest "Prevent Windows from ducking OBS monitor volume" or similar. Default-on is probably the right call, but _is_ a change in behavior. Most people won't notice/will want the new behavior though, if I had to guess.

**Comment by jp9000** [comment]
I'll modify the wording and then merge.

**Pull request closed without merging**
