### PR TITLE
固定Norsk Bokmålタイプミス (Fix Norsk Bokmål Typo)

### PR DESCRIPTION
**Pull request by JCookie20001**
固定Norsk Bokmålタイプミス

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by JCookie20001** [comment]
:)

**Comment by dodgepong** [comment]
Localization is handled in CrowdIn, not via PR. You can submit a fix here: https://crowdin.com/project/obs-studio

**Comment by Gol-D-Ace** [comment]
@dodgepong Did you even look at the commit? It's a change in the locale.ini file.

**Comment by dodgepong** [comment]
I didn't, I assumed it was an actual localization error. Whatever, I suppose this is fine.

**Comment by dodgepong** [comment]
Upon further investigation, I think the lowercase "bokmål" is correct. In English it may be capitalized, but from what I understand in Norwegian itself, it would be lowercase. I would prefer the opinion of an native speaker before accepting this (your PR message leads me to believe you are not a native Norwegian speaker).

**Comment by jp9000** [comment]
Copying and pasting from my Norwegian friend:

Just "Norsk bokmål". We rarely capitalize more than first word

So dodgepong is correct.  Closing the PR.

**Comment by elzapp** [comment]
«Norsk bokmål», yes.

**Comment by JCookie20001** [comment]
Oh.

**Pull request closed without merging**
