### PR TITLE
[Linux] ALSA Input Plugin

### PR DESCRIPTION
**Pull request by gamaral**
I wrote an ALSA input plugin a few weeks ago and so far, it has worked well.
I thought I should try to upstream it. :)

ALSA is pretty much a given in a Linux system, so there's no real dependencies added.

KNOWN ISSUES:

* ~~No I18n yet.~~
  en-US and es-ES (added, the only two languages I know).

* ~~Sometimes, some webcam PCM devices fail to open while video initialization is underway. 
       Obviously this only happens with webcams which are also being used as video sources.~~

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by gamaral** [comment]
Found a bug, fixing it. :) I'm also adding source *activate* and *deactivate* handling.

**Comment by gamaral** [comment]
PCM opening issue has been resolved.

**Comment by jp9000** [comment]
Thanks for the submission, just wanted to let you know that I may not be able to get around to reviewing this until after 0.13.0 is released.  I'm trying to get it finished before the year is over.  I usually don't review big pull requests right away -- I usually do big pull requests when a major patch is released.  0.13.0 is fair amount behind schedule so I'm trying to work as hard as I can to get it out (though I don't want to rush it due to fairly big/important changes).

**Comment by gamaral** [comment]
No worries, take your time. It'll give me time to stress test it with a few more streams and recordings. :)

**Comment by Chiitoo** [comment]
Very nice!  Awesome in fact!

I've been recording things with a script using ffmpeg, adding features to something I found someone else had done, but of course, it's nothing even close to as fancy as obs-studio is (thanks for coming to Linux, by the by!).  I finally gave a shot trying it out here (on Gentoo).  Builds and runs like a charm so far!

Only... I will not have PulseAudio installed, which brings me to this pull request (yay!).

Having applied these changes, I can add an audio capture source, but I can not record audio from a Loopback device even though the virtual device appears in the list.  I have three real cards (Xonar DG, Creative X-Fi, and HDA ATI SB/Realtek ALC889 on-board), from which two seem to lack hardware mixing and the ability to record “stereo mix/what I hear”.

Thus I do software mixing and create a Loopback device in 'asoundrc'.  I'm able to use Audacity and ffmpeg to record this way, but the correct Loopback devices don't seem to appear in obs-studio (in fact none of the PCMs created in 'asoundrc' appear in the list):

obs-studio_alsa_device-list_01

The Loopback device for recording is, with this scheme, “hw:0,1”, but only “hw:0,0“ and its subdevices seem to be detected.  The X-Fi as the sole device having the “stereo mix” option /does/ record audio, so it seems the issue is with the Loopback PCMs (or/and I'm doing something wrong!).

I'm also not seeing any devices in the Settings; the Desktop Audio Device lists are empty, and not responsive.  Is that to be expected?

Here's an [example asoundrc](https://gist.github.com/Chiitoo/6bd5688cfe6be846cd82) that I'm playing with (although I may have to retire it for now, since I have discovered that the Loopdevice might be part of the reason for my media players dropping frames at about the rate of 30 per second, or more, and other applications spending core's worth of CPU in the audio driver).

Just some thoughts, and again, thanks for the OBS Multiplatform, and thanks for the ALSA plug-in!

**Comment by gamaral** [comment]
I have a pretty similar loopback setup with asound.

Here's my copy which works a treat:

    pcm.!default {
      type asym
      playback.pcm "Monitor"
      capture.pcm "hw:Loopback,0,0"
    }
    
    ctl.!default {
      type hw
      card PCH
    }
    
    pcm.Monitor {
      type plug
      slave.pcm mdev
      route_policy "duplicate"
    }
    
    pcm.mdev {
      type multi
      slaves.a.pcm pcm.MixPCH
      slaves.a.channels 2
      slaves.b.pcm pcm.MixLoopback
      slaves.b.channels 2
      bindings.0.slave a
      bindings.0.channel 0
      bindings.1.slave a
      bindings.1.channel 1
      bindings.2.slave b
      bindings.2.channel 0
      bindings.3.slave b
      bindings.3.channel 1
    }
    
    pcm.MixPCH {
      type dmix
      ipc_key 1024
      slave {
        pcm "hw:PCH,0,0"
        rate 48000
        periods 128
        period_time 0
        period_size 1024 # must be power of 2
        buffer_size 8192
      }
    }
    
    pcm.MixLoopback {
      type dmix
      ipc_key 1025
      slave {
        pcm "hw:Loopback,1,0"
        rate 48000
        periods 128
        period_time 0
        period_size 1024 # must be power of 2
        buffer_size 8192
      }
    }

Hope it helps. :)

As for the Desktop Device bit, I also get the same thing with other plugins so I guess it's normal? Not sure, I will need to check the code for that dialog.

**Comment by Chiitoo** [comment]
Yes!

Somehow I had missed setting the slave correctly in, using your example, 'pcm.MixLoopback'.  That is, instead of 'pcm "hw:Loopback,1,0"' I'd have 'pcm "hw:Loopback,0,0"'.  Sometimes the most obvious things can be the most tricky ones to catch... or I was just super sleepy again.  Either way, feels weird I didn't catch that one!

Many thanks!  Indeed, now I can record from any and all of the displayed Loopback devices, although the “Loopback PCM Default Audio Device” produces heaps of noise.

(Now if only I can manage to stop the frame drops and other weirdness going on, I'll be quite happy about sound once more again (not related to this project).)

**Comment by gamaral** [comment]
Loopback shouldn't produce any noise. I bet you have **mic** or **line** unmuted in your main card. :)

**Comment by gamaral** [comment]
Okay, I found out why the plugin doesn't show up in 'Desktop Audio Device' and 'Mic/Aux Audio Device' under settings. OBS currently filters out anything but **pulseaudio** sources on Linux.

@jp9000 I was thinking maybe we can make OBSApp::InputAudioSource return a list, or perhaps add wildcard or regexp support to the search functions.

**Comment by Chiitoo** [comment]
> Loopback shouldn't produce any noise. I bet you have mic or line unmuted in your main card. :)

Pretty close!  It was actually due to the Loopback recording volume being way high, so it made the audio very distorted-like.

Bringing it down by about 80% normalised it.  A little curious that it only happened with the 'default' device, but it's all good now.  ^^

(This was not an obs-studio specific thing either; audio recorded via that specific device with Audacity had the same results as well.)

**Comment by jp9000** [comment]
Looks good so far from what I've seen.  Works well, and the code is clear and straight forward.  I feel this can be merged in its current state.

Two questions:

First, is there a way to differentiate between input/output devices?  For example, which is loopback and which are actual input devices?  Would be nice to separate those in to two different source types like I do with the other sources (this is mostly to make configuration more simple, if that makes sense).

Second question is I noticed that in the properties of the source it lists the same devices many times in configurations.  Is that normal?  Does each device not have a default/preferred mode and sample rate?  I'm not too familiar with how the linux audio backend works so I feel this may be a bit of ignorance on my part.  Mostly I'm trying to avoid any unnecessary conversions, and would like to use the device's current configured/preferred configuration by default if possible.

**Comment by gamaral** [comment]
Glad to hear it!

1) Yes! In fact, currently I only list and use input devices, but adding in output support wouldn't be too much trouble. I was just not sure how and where they are used in OBS (audio output devices in general).

2) Unfortunately yes, ALSA lists separate PCMs for channel configurations: default, front, surround*, iec958. That said, I could break the options them down into separate dropdowns making the selection process better.I.e. one for Card + Device and another for Channels.

   I can also add an item for the default audio input, it's currently already setup to select it, but it doesn't get listed as such in the dropdown list since the name varies.

I'll work on '2' this weekend, let me know if you want me to add the output sources ('1') also. ;)

**Comment by jp9000** [comment]
Yea, if possible separate loopback and input devices to different source types.  It may seem silly but overall it makes it more simple for configuration and general use.  It technically can be done without doing that, but mostly it's more about making things more clear for users.

**Comment by OrdinaryMagician** [comment]
I depend so much on this plugin. It's much more reliable than hackily using a ffmpeg media source to record alsa, which tends to either introduce absurd delays or simply stop recording entirely because the device isn't closed and reopened properly when changing settings.

**Comment by jp9000** [comment]
Hey gamaral - how's this going?

**Comment by gamaral** [comment]
Oops! It's almost done. I went on vacation (still am, currently in Japan eating Ramen) and totally forgot about it. I'll finish up the change-set ASAP. :)

**Comment by gamaral** [comment]
Okay, sorry for the delay. I played around with a few ideas last month, this one was the one that stuck.

Here's a [Preview Image](http://imgur.com/2JGaGQx)

**Comment by jp9000** [comment]
Okay, seems great, much better.  Going to merge and get it out there for some testing.  Thank you for taking the time to make it.  Just making one minor change though -- making it always active by default.  I made some defines to do that, hope you don't mind.  I only did that to make it consistent with the expected functionality and to make transition fade-ins sound right.

Also, will try to make it so ALSA input sources can appear in audio settings in the future at some point -- right now it can only be added in scenes, which is sort of annoying.

**Pull request closed without merging**
