### PR TITLE
add stream.me to available services

### PR DESCRIPTION
**Pull request by jseeley78**

### CODE REVIEW

**Comment by notr1ch** [comment]
The package.json needs updating too with a version number bump.

**Comment by derrod** [comment]
Please take a look at the guidelines (and other PRs) and adjust the commit message.

The service should also not be marked as common and added at the end of the list.

**Comment by jseeley78** [comment]
@derrod @notr1ch apologies; marked common as false, move service to the end, bumped the version and updated the commit message.

**Comment by jp9000** [comment]
You had a comma at the end of that last json server entry when there isn't supposed to be commas on last entries.  Be careful to watch out for that.  I'll modify this and merge it shortly.

**Pull request closed without merging**
