### PR TITLE
CI: Use ccache to speed up the build

### PR DESCRIPTION
**Pull request by juvester**
Uses [ccache](https://ccache.samba.org/manual.html#_description) to speed up recompilation.

### CODE REVIEW

**Comment by Gol-D-Ace** [comment]
Another screenshot entirely without the cache


Mac build doesn't seem to profit from this at all currently. The build was just a bit slower in the first screenshot.

**Comment by juvester** [comment]
Yeah, I noticed the same yesterday.

The time spent in `before_install` phase seems to be fluctuating a lot on osx. But time spent in the `script` phase does drop from ~170s to ~70s when using ccache.

I was using `brew install --HEAD ccache` which compiled it from source I believe (I just copy/pasted it from some other project). That probably negated all the benefits. I changed it to use the default brew ccache, let's see if that helps anything.

**Comment by juvester** [comment]
Latest result:
2017-03-03-204601_1920x1080_scrot

Interestingly the cache hit rate went up from 7.38% to 53.62% by using the normal `ccache` instead of `--HEAD` ccache.

**Comment by Gol-D-Ace** [comment]
I broke your PR by adding speexdsp

**Comment by Gol-D-Ace** [comment]
@DDRBoxman 
Yea or nay?

**Pull request merged**
