### PR TITLE
Fix VLC path detection for x64 versions

### PR DESCRIPTION
**Pull request by Gargaj**
See https://msdn.microsoft.com/en-us/library/windows/desktop/ms724072(v=vs.85).aspx

### CODE REVIEW

**Comment by OsirisNL** [comment]
What does this fix exactly? The detection with 64bit OBS works fine here.

**Comment by Gargaj** [comment]
Do you have x64 VLC installed?

**Comment by OsirisNL** [comment]
Yes, i have both 32bit and 64bit installed.

**Comment by JustGregory** [comment]
If you have both 32- and 64-bit VLC, which is launched by default?

**Comment by jp9000** [comment]
WOW6432Node is for 32bit VLC, not 64bit.  Additionally, WOW6432Node is automatically used in the 32bit version of microsoft's registry functions, so manually specifying it is never needed.

If you're having a problem, I'd suspect that VLC probably isn't installed correctly.  There definitely is not a bug or issue with 64bit or 32bit VLC plugins.

**Pull request closed without merging**
