### PR TITLE
Add option to start replay buffer when you start streaming

### PR DESCRIPTION
**Pull request by cexikitin**
Copied how the auto recording feature was implemented.

### CODE REVIEW

**Comment by Gol-D-Ace** [comment]
I see a few issues here.

Situation:
Advanced Output doesn't support the Replay Buffer yet. (User is using Advanced Output instead of Simple Output.)
Custom Output (FFmpeg) might never support Replay Buffer.
User didn't enable the Replay Buffer.

All situations will end up in not starting the Replay Buffer while the checkbox says that it will.

**Comment by cexikitin** [comment]
Looks like hotkey for saving the replay buffer is hidden when we are not in a state to use it, the same could be applied to the checkboxes.

**Comment by Gol-D-Ace** [comment]
Hiding is an option but probably not the best.
Graying it out might be better.

You will still know that the option exist that way.

**Comment by cexikitin** [comment]
@Gol-D-Ace Now the checkboxes are greyed out when either output mode is set to advanced or the replay checkbox is unchecked.

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
Resolved conflicts and merged.

**Comment by PadelMagazine** [comment]
Hi, 
I use the last version of OBS STUDIO. And impossible for me to understand 2 things :
1/ How to integrate an video MP4 for example. Each time i do it i have a black screen in preview and not the video. 
2/ How can i make a replay with the NEW VERSION ? It's different that the older one. 
Thanks for you help
Franck

**Pull request closed without merging**
