### PR TITLE
Prevent crash when adding an invalid regex to Automatic Scene Switcher

### PR DESCRIPTION
**Pull request by RytoEX**
This PR addresses [Mantis Bug 644](https://obsproject.com/mantis/view.php?id=644).  OBS Studio 0.16.0-0.16.2 would crash if you tried to add an invalid regular expression as the window title in the Automatic Scene Switcher.  This PR prevents that crash with a try-catch.  Instead of crashing, a warning message is now displayed when an invalid regex is entered.

As always, reviews and feedback are welcome.  Maintainers are free to edit, accept, or reject.

### CODE REVIEW

**Comment by Xaymar** [comment]
Perhaps add automatic conversion of detected windows to proper regex? Escape +,-,[,],{,},(,),*,?,!,: and ; to make it work. There may be some others I have missed.

**Comment by RytoEX** [comment]
Not sure what you mean.  Do you mean to get the list of current window titles and convert those to valid regex?  Or do you mean check a user-entered regex and convert it to a valid regex if it was invalid?

If you mean the former, that could probably be done, though that's not what this was meant to address.  You would probably also run into the issues I'm about to address below...

If you mean the latter, I think you'd have to write the code for that manually, and you'd have to cover every possible invalid case (unmatched brackets/braces/parentheses, bad character class, bad character range, etc.), and it's pretty easy to mess up regex, especially when you don't know you're writing regex and you're expecting things like * to act as a simple wildcard (Windows, shell glob, etc.) instead of a repetition operator.

As far as I'm aware, the C++ regex library doesn't have any kind of validation/correction functions exposed, it just throws errors when your regex is malformed.  Some of those errors _do_ indicate specific invalid cases, which would help if you wanted to try to fix regex strings, but you'd still have to parse the string and try to fix it without accidentally "fixing" the wrong thing and just breaking it some other way (escaping an already escaped character, or matching an escape parenthesis/bracket/brace, for example).

**Comment by Xaymar** [comment]
I meant the former, but if this wasn't meant to address that then ignore my request.

**Comment by RytoEX** [comment]
Commits squashed per request by @jp9000.

**Comment by Temcoin** [comment]
How can I use a wildcard in the window title without OBS crashing? I thought that was supported.

**Comment by RytoEX** [comment]
@Temcoin You can use wildcards, but you have to use valid regex, not Windows/shell-style patterns.

".*" is a valid regex that is equivalent to the "*" used in Windows/shell-style patterns.

For more info, read the Mantis bug noted in the [initial comment](https://github.com/jp9000/obs-studio/pull/642#issue-180447505), or read up on regular expressions.  There are plenty of resources.

http://www.regular-expressions.info/
https://regex101.com/
http://www.regexpal.com/
http://regexr.com/

**Pull request merged**
