### PR TITLE
UI: Add functions and events for Studio Mode into the Frontend API

### PR DESCRIPTION
**Pull request by Palakis**
This Pull Request aims to add several features to the Frontend API:

- Functions: enable, disable and get Studio Mode status + get and set the current preview scene
- Events: on Studio Mode enable and disable + when the currently previewed scene in Studio Mode changes.

Please let me know of any issue with code style or API design.

### CODE REVIEW

**Comment by jp9000** [comment]
Great PR, but I'm not sure why you made enable/disabling studio mode separate functions.  It should be called something similar, like obs_frontend_set_preview_program_mode(bool enable).

**Comment by jp9000** [comment]
Also, obs_frontend_preview_mode_active should probably be obs_frontend_preview_program_mode_active instead.

**Comment by jp9000** [comment]
Also, this PR should be squashed in to one commit.  (Sorry for the multiple replies)

**Comment by Palakis** [comment]
Thanks for reviewing this! Code updated and commits squashed.

**Pull request merged**
