### PR TITLE
obs-filters: Add "Color Grading" filter

### PR DESCRIPTION
**Pull request by mape**
This allows for color grading based on a color look-up table. Commonly
used to color correct and/or grade video that has been shot in Log.

Example video @ https://h.ma.pe/obs_color_grade.mp4

### CODE REVIEW

**Comment by mape** [comment]
Some LUTs to test with:

https://h.ma.pe/lut/posterize.png
https://h.ma.pe/lut/blackAndWhite.png
https://h.ma.pe/lut/tealLowsOrangeHighs.png
https://h.ma.pe/lut/redIsolated.png
https://h.ma.pe/lut/original.png

**Comment by SuslikV** [comment]
"Color Grading" hardcoded name of the filter. I think, you need change this to support translations.

**Comment by mape** [comment]
Updated to use "[ColorGradeFilter](https://github.com/jp9000/obs-studio/pull/747/commits/953b8d04d304b41ce9f0bd87e144ccd56ed0f40b#diff-c0e400059b6051c4e7fdca9053b03bd2R2)" instead of "Color Grade"

**Comment by c3r1c3** [comment]
Wouldn't this be better called "Apply [1D/3D] {External} LUT"?

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
Mind if I include the LUT files with it?

**Comment by mape** [comment]
I don't mind at all.

**Pull request closed without merging**
