### PR TITLE
linux-pulseaudio: Get correct default device

### PR DESCRIPTION
**Pull request by alexandrevicenzi**
This fix [#794](https://obsproject.com/mantis/view.php?id=794) and [#855](https://obsproject.com/mantis/view.php?id=855).

This is an improvement of PR #796.

### CODE REVIEW

**Comment by benklett** [comment]
I have tested this PR and it works great. Thank you.

I am sorry for not answering on your last PR anymore. The problem was, I could not approve your PR. I was just testing it. Hope you can understand.

**Comment by alexandrevicenzi** [comment]
@benklett it's ok, the last PR wag bug, this one I think it's ok.

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by alexandrevicenzi** [comment]
@reboot could you take a look into this?

**Comment by alexandrevicenzi** [comment]
@jp9000 Any change to get a review from one of the admins?

**Comment by jp9000** [comment]
Sure, I'll get back to you in a day or two.  Sorry on the wait.

**Comment by jp9000** [comment]
I made a slight modification to this PR -- I noticed you were appending the "Default" item to the end of the list -- I changed it so it adds at index 0 instead.  Also with your strcmp it might be good to check to make sure the variable you're comparing isn't null, otherwise the strcmp will segfault if it's null, so I added a null pointer check there.

Merging with those changes shortly -- it'll say "closed from [commit hash]".

**Comment by alexandrevicenzi** [comment]
@jp9000 Thanks for the feedback. I just refactored some code and this implementation was based on the Windows WASAPI plugin.

**Pull request closed without merging**
