### PR TITLE
Remove get monitors

### PR DESCRIPTION
**Pull request by wt**
The functionality around probing for monitors can use Qt instead of a per-platform implementation. That's what this change does.

### CODE REVIEW

**Comment by wt** [comment]
I just updated this PR as I incorrectly implemented the logic pertaining to restoring the previous window location when the app is launch. Everything should be ready to go now.

**Comment by wt** [comment]
Squashed and updated per our discussion on IRC.

**Comment by wt** [comment]
All autos removed.

**Comment by reboot** [comment]
This change breaks the full screen projector for me on Linux

Error
Left: Current master
Right. After reverting f3eb8aacfeb9c1f2f93b1bea0003e1279f23adc6

**Pull request merged**
