### PR TITLE
obs-plugins: Add solid color source

### PR DESCRIPTION
**Pull request by cg2121**
This allows users to quickly add a solid color to a scene without them having to create images.

### CODE REVIEW

**Comment by cg2121** [comment]
For some reason filters don't work with this.

**Comment by Gol-D-Ace** [comment]
+	obs_data_set_default_int(settings, "color", 0xFFFFFFFF);
+	obs_data_set_default_int(settings, "width", 800);
+	obs_data_set_default_int(settings, "height", 600);

Should be translatable.

**Comment by jp9000** [comment]
The reason why filters probably don't work properly is because the filter isn't marked as a custom drawn source.  You might want to add that capability flag in there or'ed with OBS_SOURCE_VIDEO.

**Comment by cg2121** [comment]
Everything is working now.

**Comment by jp9000** [comment]
I'm moving this to the image-source plugin, if you have misc sources like this you can just put them in image-source instead of creating new modules.  Probably best to cut down on modules.

**Comment by jp9000** [comment]
Also cg2121 just wanted to say for the record that you're amazing, this is definitely nice to have.

You just seem to keep going, adding high-quality stuff non-stop, even if I don't always merge everything.  You are awesome.

**Pull request closed without merging**
