### PR TITLE
graphic-hook: Bug fix in graphics-hook.c

### PR DESCRIPTION
**Pull request by zhk**
Fixed a potential memory bug in graphics-hook.c
tex1_offset may changed after aligned to 256 addresses. This makes the total size increase.

### CODE REVIEW

**Comment by jp9000** [comment]
So, what you are proposing with this fix is basically that (tex2_offset + aligned_tex) has a possibility of being outside of the boundary of the allocation -- in other words, you felt that the total_size could potentially be insufficient depending on what the pointer alignment was, the texture's pitch/height, and the size of the shmem_data structure was.

So, to find out whether that is actually true or not, I programmed a test using a variety of combinations of hypothetical starting pointer addresses (basically an offset of 0-31 just to be even more complete), texture sizes (1-4000 for both pitch and height), and structure sizes (of a hypothetical "shmem_data" struct, but for the sake of completeness tested sizes of 1-1000) to see whether (tex2_offset + aligned_tex) would ever be outside of the allocation's boundary.  Via that test, it never exceeded the pointer's memory boundary.  In other words, you're trying to fix something that wasn't broken.

I'm assuming that this fix was made without actual testing or any actual encountered case where this fixed a problem you were having.  In the future, please make sure to perform tests and provide proof via those tests before attempting a fix of what you think may be a bug.

**Comment by jp9000** [comment]
I really have to apologize, I should have asked you to clarify further before assuming what it was you were having problems with.  The reason why I was confused is because your original code just added a "+ 32" to the "total_size" variable, which was an incorrect fix: https://github.com/jp9000/obs-studio/pull/1202/commits/9bff5eaeee495b0ad96d08941f04daba5261c00c -- that commit would not fix align_pos being the wrong value as you state.  That commit made me incorrectly assume that you thought "total_size" was insufficient size for the memory allocated, which was not true if you don't modify the "align_pos" code.  In that commit I just linked, there was no change to "align_pos", hence my misunderstanding.

So I understand now -- the problem wasn't that the total memory size was insufficient and that the memory was out of bounds, the problem was that the offset of the first texture can intersect with the structure (depending on what the pointer's address was).  I see the problem.  Technically, the correct fix for this is here:  https://github.com/jp9000/obs-studio/commit/8a16fa8341821689e04f5a46cc3d06f44a46caef

**Comment by zhk** [comment]
Yes, the bug has gone now. Thanks.

**Comment by jp9000** [comment]
Again I really apologize for the misunderstanding.  Thank you for reporting this bug.

**Comment by cpuwolf** [comment]
https://obsproject.com/mantis/view.php?id=1168

is it same issue here?

**Pull request closed without merging**
