### PR TITLE
Update to recommended settings for Hitbox.tv

### PR DESCRIPTION
**Pull request by LevelPulse**
Hitbox.tv just updated their recommended settings, it is now main instead of fast.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by Gol-D-Ace** [comment]
Nope. Hitbox wants high. It complains about main in the Dashboard and wants high.
Your information must be a bit outdated.

**Comment by jp9000** [comment]
I could be totally mistaken, but I'm pretty sure it's still "high", yea.

**Comment by Gol-D-Ace** [comment]
Further information also mentioning high: http://help.hitbox.tv/customer/en/portal/articles/1320003-obs-setup

**Pull request closed without merging**
