### PR TITLE
libobs: Fix multi-channel speakers layouts

### PR DESCRIPTION
**Pull request by SuslikV**

### CODE REVIEW

**Comment by SuslikV** [comment]
https://github.com/jp9000/obs-studio/blob/master/plugins/decklink/decklink-device-instance.cpp#L51 
 -> should be reviewed.

**Comment by pkviet** [comment]
well spotted. LGTM

**Comment by jp9000** [comment]
The latter two commits do not conform to commit message standards.

**Comment by SuslikV** [comment]
commit titles?

**Comment by OsirisNL** [comment]
He means the last two commits, they don't specify what part it applies to, the first one specifies libobs.

**Comment by SuslikV** [comment]
I will give up at this time. I don't know how to make it possible from the web from. I am amateur, not the pro, thus all commits were made from the web interface. The changes doesn't affect many users as I understand.

Let's say it was bug report not the PR itself.

**Comment by pkviet** [comment]
ok i will do it then; and actually I realized a change should be made for 2.1 :  SPEAKERS_2POINT1:          return AV_CH_LAYOUT_2POINT1 ==> should be  AV_CH_LAYOUT_SURROUND
Reason is ffmpeg aac encoder directly support 2.1 only on master; while earlier versions of ffmpeg for three channels support only AV_CH_LAYOUT_SURROUND = FL FR FC ; it is not 2.1 but it is working fine because the LFE channel is encoded as a SCE without low freq filters.

**Comment by jp9000** [comment]
I didn't mean for you to delete this, the code seemed fine.  To fix commit titles, you can do so via an interactive rebase with git.  It sounds intimidating but it's actually pretty simple.  You'd type for example "git rebase -i master", and then you'd mark the commits you'd like to reword as "reword", then it'll allow you to edit the commit messages for them again.

I probably would have helped and fixed it for you, but I've just been busy getting this deployment out these past few days.  It's just the speaker layout so it's not a huge deal, although if you have time feel free to recreate the PR and I'll merge it.

**Comment by pkviet** [comment]
ffmpeg native aac encoder supports all layouts in avutil/channel-layout.h on master head.
But on earlier versions including 3.4 which ships with obs on windows only the following layouts are supported :  (extracted from libavcodec/aacenctab.h )

static const int64_t aac_normal_chan_layouts[7] = {
    AV_CH_LAYOUT_MONO,
    AV_CH_LAYOUT_STEREO,
    AV_CH_LAYOUT_SURROUND,
    AV_CH_LAYOUT_4POINT0,
    AV_CH_LAYOUT_5POINT0_BACK,
    AV_CH_LAYOUT_5POINT1_BACK,
    AV_CH_LAYOUT_7POINT1,
};

This follows from aac spec.
libfdk_aac and coreaudio aac follow the spec also and therefore for 3 channels, treat it as FL+FR+FC ;
but as explained above this can still be used for 2.1 because LFE gets encoded as FC (as an SCE channel in spec terms).

I'll fix that later today.

**Comment by SuslikV** [comment]
The restrictions of the AAC is only the limit of the encoder itself. The Studio may operate wider number of channel setups. Specify, was it intended to use only AAC for multi-channel audio or not? A for me, I think only: stereo; 5.1 and 7.1 needed at all (even mono is obsolete).

**Comment by pkviet** [comment]
> The restrictions of the AAC is only the limit of the encoder itself.
    
Right
For instance mf-aac does not support the full aac spec.    
On the other side of the spectrum, the (native) aac ffmpeg encoder supports up to 16.0 (on master only, not on current release 3.4), (aac spec supports up to 48 channels ; aac ffmpeg is the only encoder to go beyond 8 channels).    
   
> The Studio may operate wider number of channel setups. 

It could. I had added up to 16.0  in my PR on surround audio but Jim felt it was too much; I do agree that's it's a very specific use-case that i have.   

> Specify, was it intended to use only AAC for multi-channel audio or not?    

No. If other codecs support surround , they should work.  (used libopus, ac3, vorbis, pcm without issues)  
But this misses the point which is that you need to have your speaker layouts tailored to aac spec since this is the default audio encoder.    

> A for me, I think only: stereo; 5.1 and 7.1 needed at all (even mono is obsolete).

Maybe for your case uses.   
4.0 is useful for ambisonics == order 1 ===> can be used to stream to FB live 360 with spacial audio, if you have an ambisonics capture device.   
I personnally use with decklink capture card all the range of speaker layouts provided by OBS (and also beyond).

**Pull request closed without merging**
