### PR TITLE
UI: add Hide to Tray instead of Minimize option

### PR DESCRIPTION
**Pull request by SuslikV**
* UI: add Hide to system tray instead of minimize to Task bar option.
Enables new option to control Hide on minimize window.

* UI: changes to window management during hide to tray.
New behavior:
1. Ignores Hide to tray when any modal dialog or message box is visible;
2. All child dialogs preserved upon hiding (doesn't forced to close);
3. Switching virtual desktops may cause window minimize forced and thus "Hide" triggered if "Hide to system tray instead of minimize to task bar" is checked. Possible workaround: click "Show" from the tray menu.
4. Fullscreen Projectors not switching off on hiding to tray (doesn't forced to close).

### CODE REVIEW

**Comment by SuslikV** [comment]
Not complete. Maybe later.

Only web interface of the github was used, so this strange formatting...

**Comment by SuslikV** [comment]
Small changes ahead.

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
Just for future reference, try not to break code styling, make sure all commits are compilable, fix up commits and keep related things in the same commit and don't have fixup commits.  I had to merge all your commits together and then split them myself.  I don't want to have to spend time doing that, but this PR had a number of issues that I didn't want to wait for so I fixed it all up myself.

The Qt "foreach" helper isn't necessary because C++11 has ranged for loops that work with Qt containers.

Super long variable names aren't really preferable, like list_of_visible_messageBoxes and things like that, can just be visMsgBoxes.  Also, combining the underscore_case with CamelCase feels strange there too.  Try to avoid that.

You had a fair amount of trailing whitespace in your code.  Avoid that by doing a git diff command on your code so it can point it out.

Your coding style and indenting style in general was just unusual compared to the rest of the code.

You also had unused code that was just sitting there commented out that should have been removed.

Please see the three commits c15099d, 6dfec8e, and 8789e04 to see how I'd normally like things -- both in terms of working compilable commits, commit messages, and coding style.  If things are the way I like, PRs won't be delayed for merging and I can just test, review, and hit the merge button ideally.  Otherwise I may delay a PR to fix it up myself if it feels necessary.

**Comment by jp9000** [comment]
Woops, forgot to set you as the original author of those commits.  Fixed that while things were still fresh.  abe4bfd, d473b2d, and 7eee8de

**Pull request closed without merging**
