### PR TITLE
Please add DJlive.pl - polish platform for DJ`s to services.json

### PR DESCRIPTION
**Pull request by thekrzos**
Added DJlive.pl - polish platform for DJ`s

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by Gol-D-Ace** [comment]
Hi. Please follow the guidelines for commit titles.

Commit title should be formatted like this:
`rtmp-services: Add DJlive.pl to services`

Also you missed to increase the version number in the package.json like here: https://github.com/jp9000/obs-studio/commit/c95beb2920d220f7cf7b1d6c4fa01ed699846afb

**Comment by Gol-D-Ace** [comment]
Oh and I think you got some tabs in there.
This file only uses spaces for formatting.

**Comment by thekrzos** [comment]
Ok, done

**Pull request merged**
