### PR TITLE
Additional streaming service that is used around the world, stre.am/enterprise

### PR DESCRIPTION
**Pull request by hoosierfan24**

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by notr1ch** [comment]
This is not a common service so the common flag should be omitted. You will also need to increment the version number of the package (see https://github.com/hoosierfan24/obs-studio/blob/762f8c8c2fbfe772a615cd84fb6429a423d7d764/plugins/rtmp-services/data/package.json) and format the commit message appropriately (example: https://github.com/jp9000/obs-studio/pull/545/commits)

**Comment by hoosierfan24** [comment]
Thanks for the feedback. Will make changes shortly, what are the requirements to be listed as common? The app is used by professional sports teams, celebrities, news publications, and influencers.

http://www.usatoday.com/story/tech/2016/05/02/ditch-facebook-branding-stream-live-video/83816300/

**Comment by notr1ch** [comment]
Services marked "common" are those that are going to be one of the first choices a user is looking to use when installing OBS (eg "I want to stream to twitch / facebook / youtube"). As the main focus of stre.am appears to revolve around the app, it seems most users will never need to use RTMP ingesting.

**Comment by jp9000** [comment]
The "common" stuff was done because we don't want to show all the services by default.  You may wonder why, but let me explain.

You know, originally I never had any intention of making anyone think we're treating any service as "special".  I remember I used to list every service that simply asked me to be listed, equally.

Then, I started getting requests, lots, and lots of requests, constantly.  They'd email, post on our forums, ask in our chat, constantly.  A lot of services seem to view it as free advertisement.  They want to be listed to get their name out there to our users.

But where it started to take a turn for the worst was when there were sites that did porn, heavy monetizing, and even sites that seemed heavily centered around vaping (of ALL things to have a streaming site for) started asking -- sometimes demanding -- to be listed.  Sometimes they ask us to write in their service-specific APIs for them, which is now possible but quite frankly I just don't have time to do for every lesser service that asks.

At some point I came up with this quick solution -- newer sites that we don't know much about could have their stuff listed, but the user would simply have to click a checkbox that says "Show all services" to make them visible.  It required an extra step of clicking that checkbox for users, but they'd be in there and have servers listed.

Honestly, it's not a good solution.  It's an inconsistent solution.  I very much dislike adopting any sort of indecisiveness or inconsistency in behavior and/or actions.

I have an idea for a better solution however -- for newer sites I'm probably just going to add in a scripting solution to allow those other sites to let them make scripts that users download to automatically set up ingests/API/etc for their users in the program or something for their users.  Right now it's a bit difficult to maintain a master list anyway, as the "lesser" services often forget to update their ingests and expect *us* to write in their API for them.  One service completely died and was left in the list for weeks after because no one used it and no one told us anything until then.

Though honestly, I'm not sure what the "best" solution is that would make everyone happy.  There's always someone who's going to be unhappy that they aren't treated as good as Twitch and Youtube.

Just ranting here.  Fact is, I don't want to have to continually update the main repo for new services.

**Comment by jumoog** [comment]
maybe it's a good idea to move that plugin in a own repo and use github as update source

**Comment by abdurrazzacqk1** [comment]
Dear sir
I. Feel. There is no use of receiving communication from you. Please stop sending further. Emails from you. Unsubscribe.

-----Original Message-----

**Comment by hoosierfan24** [comment]
Thanks for the explanation Jim! Looking forward to getting added as a service, just let me know if there are any additional changes I need to make.

**Comment by robske110** [comment]
@jp9000 If you don't want to continuously update the repo, how about putting this already in a json style stuff on a server. So it just gets the file and you can update it always.

**Pull request closed without merging**
