### PR TITLE
UI, obs-qsv11: Fix build in VisualStudio 2017

### PR DESCRIPTION
**Pull request by e00E**
OBS did not build out of the box in VS2017 but it does with these
changes. This was all done on/in x64.

Please check if the changes are sane as I do not know the OBS code well.

Without the changes the following errors are produced when building:
```
2>D:\Documents\programming\OBS\obs-studio\plugins\obs-qsv11\QSV_Encoder.cpp(173): error C3861: '__cpuid': identifier not found
2>D:\Documents\programming\OBS\obs-studio\plugins\obs-qsv11\QSV_Encoder.cpp(183): error C3861: '__cpuid': identifier not found

1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(661): error C4839: non-standard use of class 'BPtr<char>' as an argument to a variadic function
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(661): note: the constructor and destructor will not be called; a bitwise copy of the class will be passed as the argument
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(375): note: see declaration of 'BPtr<char>'
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(661): error C2280: 'BPtr<char>::BPtr(const BPtr<char> &)': attempting to reference a deleted function
1>D:\Documents\programming\OBS\obs-studio\libobs\util/util.hpp(33): note: see declaration of 'BPtr<char>::BPtr'
1>D:\Documents\programming\OBS\obs-studio\libobs\util/util.hpp(33): note: 'BPtr<char>::BPtr(const BPtr<char> &)': function was explicitly deleted
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(665): error C4839: non-standard use of class 'BPtr<char>' as an argument to a variadic function
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(665): note: the constructor and destructor will not be called; a bitwise copy of the class will be passed as the argument
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(375): note: see declaration of 'BPtr<char>'
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(665): error C2280: 'BPtr<char>::BPtr(const BPtr<char> &)': attempting to reference a deleted function
1>D:\Documents\programming\OBS\obs-studio\libobs\util/util.hpp(33): note: see declaration of 'BPtr<char>::BPtr'
1>D:\Documents\programming\OBS\obs-studio\libobs\util/util.hpp(33): note: 'BPtr<char>::BPtr(const BPtr<char> &)': function was explicitly deleted
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(767): error C4839: non-standard use of class 'BPtr<char>' as an argument to a variadic function
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(767): note: the constructor and destructor will not be called; a bitwise copy of the class will be passed as the argument
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(375): note: see declaration of 'BPtr<char>'
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(767): error C2280: 'BPtr<char>::BPtr(const BPtr<char> &)': attempting to reference a deleted function
1>D:\Documents\programming\OBS\obs-studio\libobs\util/util.hpp(33): note: see declaration of 'BPtr<char>::BPtr'
1>D:\Documents\programming\OBS\obs-studio\libobs\util/util.hpp(33): note: 'BPtr<char>::BPtr(const BPtr<char> &)': function was explicitly deleted
```
Or in pretty:
capture

The `QSV_Encoder.cpp` errors seem to stem from the `__cpuid` function moving into the `intrin.h` header. I do not know if my change will break the VS2015 build, someone please test this. If yes, then it probably needs to be included conditionally only via the preprocessor.

The `win-update.cpp` errors stem from passing `BPtr<char>` to `strprintf`.  I believe before the parameter was automatically converted to `* char` before but not anymore in this VS version so I made the conversion explicit.

After fixing the errors, some warnings remain. I do not know if they are serious and need to be fixed. If they should be, I could try doing that too, please tell me.
```
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(493): warning C4458: declaration of 'manualUpdate' hides class member
1>d:\documents\programming\obs\obs-studio\ui\win-update\win-update.hpp(9): note: see declaration of 'AutoUpdateThread::manualUpdate'
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(499): warning C4458: declaration of 'manualUpdate' hides class member
1>d:\documents\programming\obs\obs-studio\ui\win-update\win-update.hpp(9): note: see declaration of 'AutoUpdateThread::manualUpdate'
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(539): warning C4459: declaration of 'provider' hides global declaration
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(33): note: see declaration of 'provider'
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(641): warning C4840: non-portable use of class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' as an argument to a variadic function
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(641): note: 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string' is non-trivial
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\xstring(1923): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string'
1>D:\Documents\programming\OBS\obs-studio\UI\win-update\win-update.cpp(641): note: the constructor and destructor will not be called; a bitwise copy of the class will be passed as the argument
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\xstring(3997): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
```
captu2re

### CODE REVIEW

**Comment by e00E** [comment]
Also of note is that QT 5.8 does not build in VS2017, but 5.9.0beta3 (which was available in the QT installer) does and this is what I used.

**Comment by e00E** [comment]
With the most recent commit there are no more warnings.

**Comment by e00E** [comment]
The continuous-integration thing above failed, but it does not seem related to my change. Navigating to its log I see
```
The command "./CI/install-dependencies-osx.sh" failed and exited with 56 during .

Your build has been stopped.

/Users/travis/.travis/job_stages: line 150: shell_session_update: command not found
```
which as far as I can tell has nothing to do with my patch.

**Comment by e00E** [comment]
Looks like a new build was triggered and now the builds pass.  I do not know what caused it to fail before.

**Comment by jp9000** [comment]
Going to modify this PR slightly, and then merge.

You changed some BPtr<> variables to use the dereference operator when used as %s printf parameters, which would cause a crash.  Instead, I added a .Get() function to the BPtr<> class and now have those use .Get() when used as printf parameters to ensure the pointer is returned.

**Pull request closed without merging**
