### PR TITLE
UI: Fix freeze when reordering filters

### PR DESCRIPTION
**Pull request by cg2121**
I opened a new PR because it said I couldn't reopen the old one because I forced pushed to the branch. After messing around with the code for a couple of hours, I figured out that you need to hide the widget before deleting it.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by cg2121** [comment]
If you close and reopen the filters dialog, and then reorder the filters it will still freeze. But if you click on a filter and reorder it will work fine. I believe it freezes because the properties dialog is hidden when first opening the dialog. If the properties dialog could be shown when opening the dialog, I believe we would be fine.

**Comment by cg2121** [comment]
I've got everything to work now.

**Comment by SuslikV** [comment]
A bit strange, I cannot repeat:
"If you close and reopen the filters dialog, and then reorder the filters it will still freeze."
with the first edition **view->hide();** only.

Maybe system related? In my case Filters dialog window always start with last filter in the list selected. Win7x32.

Anyway, this is attempt to fix:
1) https://obsproject.com/mantis/view.php?id=641
2) https://obsproject.com/forum/threads/filters-window-scales-improperly.57467/

**Comment by jp9000** [comment]
The bug was actually unrelated to the code in the UI.  It was caused by a reverse mutex hard lock (two threads locking two different mutexes in opposite order, causing a hard lock).   	This was due to the fact that the old view that deleteLater was being called on would linger, causing two property views to be displayed at the same time, resizing the filter dialog's display view.  e541e17 and 580f38a fix the bug properly.

**Pull request closed without merging**
