### PR TITLE
Fixes for Authenticated RTMP streams

### PR DESCRIPTION
**Pull request by chaironeko**
This fixes all the problems I can find with authenticated streams hanging in the "Connecting" state.
If I need to make *any* changes to these commits, I will thoroughly test them again.
I have tested:
 1) connecting to the server
 2) Reconnecting to the server
 3) Connecting with a blank stream key
 4) Attempting to connect with invalid credentials

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
ok to build

**Comment by chaironeko** [comment]
New full list of things tested:
* Connecting to custom server with auth
* Manual reconnection to custom server with auth
* Automatic reconnection to custom server with auth
* Connecting to custom server with blank stream key
* Attempted connection to custom server with invalid credentials
* Connecting to Twitch
* Manual reconnection to Twitch
* Automatic reconnection to Twitch

**Comment by chaironeko** [comment]
Added commit to fix warning in b64enc() and retested as before.

**Pull request merged**
