### PR TITLE
UI: Revision to streaming/recording indicator

### PR DESCRIPTION
**Pull request by cg2121**
This is a revision from my original idea for the indicators. Instead of the buttons changing colors, icons are now used.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by reboot** [comment]
The image looks rather large compared to the text. I add 4px padding to the image on each side and that made it look much nicer. Also Qt automatically downscales the image to match the text size, but it never upscales the image. So it is probably good to make the source image larger like 64px or something, so Qt can downscale it for larger font sizes. If the font is larger then the image and it is not upscaled then it would be too small.

For color blind people it would probably be nice if the stopped icon had a different shape, like a square that is usually used for "Stop" on video/audio players.

**Comment by cg2121** [comment]
My intention was to make to icons look like a red LED light. With the icons being 16x16, this makes them   a consistent size with other icons.

**Comment by cg2121** [comment]
I have now made the icons 64x64, so they can scale to whatever size they need to be.

**Comment by cg2121** [comment]
As for color blindness, I believe as long as the active and inactive icons are completely different colors, in this case red and black, I think we should be fine.

**Comment by kkartaltepe** [comment]
The icon committed isn't monochrome red so it should be fine even for color blind individuals. Feel free to give http://www.color-blindness.com/coblis-color-blindness-simulator/ a whirl.

**Comment by reboot** [comment]
I added a 4px padding to the 16x16 icon, that is 25% of the original icon size. It seems you added a 4px padding to a 64x64 icon which is much less and almost not noticeable. A 25% padding makes a big difference.

**Comment by cg2121** [comment]
It does look better when I put the 25% padding on the icons.

**Comment by rikai** [comment]
Fwiw, i actually preferred the idea of the previous commit, at least as i understood it, not having actually tested it in master. From what i understood, it changed the color of the whole button when recording, correct?

In the our use case for OBS for my job, the OBS machine is all the way across the room and would be being controlled via a hardware switcher in the long term. So having a strong visual indicator, like changing the color of the entire button color, which is easily visible from a distance, would actually have been preferred.

The icon solution is essentially what wirecast does, and has been a problem for us verifying our recording status at a glance from the other side of the room and seeing the previous commit was a nice bonus for us in our slow transition to OBS.

Not saying this approach is a bad one, just offering a bit of input from another perspective. :+1:

**Comment by cg2121** [comment]
I have just noticed that the lines were greater than 80 characters. I have resolved this now.

**Comment by jp9000** [comment]
As for this PR, I'm just not feeling this proposed change unfortunately.  Everything we try here still makes me feel uncomfortable with it.  It just doesn't look/feel right to me.  Besides, your system tray addition sort of solves this to some extent anyway.

We can try to think of some alternatives later, but for now we should just shelve this idea for the time being.

**Pull request closed without merging**
