### PR TITLE
obs-filters: Add audio compression filter

### PR DESCRIPTION
**Pull request by jrm780**
Implemented a compressor audio filter to allow for built-in, improved audio control.  Provided UI text for US English.
compressor

### CODE REVIEW

**Comment by Gol-D-Ace** [comment]
@jrm780 
If you want I can push the changes that I mentioned to your repos master.

**Comment by jrm780** [comment]
@Gol-D-Ace Sorry! I just saw your message now. No worries, if my changes resolved the issues you've mentioned in review. Otherwise, feel free to make any changes you feel are necessary.

**Comment by Gol-D-Ace** [comment]
Well I goofed up...
Pushing through this wasn't a good idea...

**Comment by jrm780** [comment]
Haha, no worries. I still have everything locally. What do you need me to do, in order to get this change integrated?

**Comment by Gol-D-Ace** [comment]
I also have it...
I just pushed the clean master into your master instead of the changed branch....

Please push your changes to your master again so I can see your current state.

**Comment by jrm780** [comment]
^ Done

**Comment by Gol-D-Ace** [comment]
I just pushed the fixed version to your master.
I can't do an actual code review but it will now build and the commit title is also in the right format.

**Comment by Gol-D-Ace** [comment]
What i exactly did was this.

git remote add jrm780 URL
git checkout -b compression_filter
git pull jrm780 master
git reset --hard  commithash | Before the merge commits (getting rid of the merge commits)
Added your filter to the CMakeLists.txt
git add * | Because this was the only change. No special staging required.
git commit --amend | For amending your commit. Adding the missing CMakeLists.txt entry and renaming the commit.
git push -f jrm780 master | The master part was the issue because i pulled your changes into a new branch named compression_filter . Ideally you would create a branch for a new feature and don't do this directly in master.

**Comment by hwdro** [comment]
Might want to move float *env_buf from compressor_filter_audio() into the compressor_data struct, have it allocated/freed in create/destroy.

**Comment by jrm780** [comment]
@hwdro Thanks for the feedback! That definitely makes sense. Is the number of samples guaranteed to be the same for each call to `compressor_filter_audio()` throughout the lifetime of the filter? I was looking at where it's fed audio data, but I want to make sure there aren't any edge-cases I'm missing. If that's the case, is there already a convenience function I should use to retrieve the buffer size?

**Comment by hwdro** [comment]
As far as I remember , there's no way to retrieve the actual number of frames (in filters plugin context).
Speaking from my own experience, audio sources that play nice have a frame size of samples_per_sec * 0.01 (basically the buffer size / channel holds 10ms worth of audio). So, you can preallocate a buffer the size of num_channels * samples_per_sec / 100, and, if necessary , reallocate it (brealloc) in compressor_filter_audio if audio->frames is bigger than the previous frame size.

**Comment by jp9000** [comment]
Fixing code styling, then merging.  (Tabs for indent, spaces for alignment)

**Pull request closed without merging**
