### PR TITLE
Misc. typo fixes

### PR DESCRIPTION
**Pull request by luzpaz**
some doxy and some non-user facing

### CODE REVIEW

**Comment by reboot** [comment]
A lot of the fixes you did seem to be in dependencies, those are kind of pointless, because they will be overwritten the next time the dependency is updated from the source. You better contribute those to the original projects.

**Comment by luzpaz** [comment]
@reboot can you cherry pick the ones that are relevant to you? i tried to weed out the deps since i thought many of them were in modules/

**Comment by Fenrirthviti** [comment]
The only relevant typo I see here is cmake/Modules/CopyMSVCBins.cmake and it's just a comment.

The rest are all dependencies and not worth the effort as @reboot mentioned.

**Comment by jp9000** [comment]
Thanks, but I don't think typos/misspellings in comments are really all that critical.  Especially ones in dependencies.

**Pull request closed without merging**
