### PR TITLE
ui: Change default recording format to MKV from FLV

### PR DESCRIPTION
**Pull request by EntranceJew**
Each day someone records with OBS and doesn't know what FLV is or why they have one now. Even worse, someone will then deliver that FLV to someone else without having any idea what to do with it.

For just one commit a month you could end this silent tragedy happening in your neighborhoods.

please help my adorable spongey brained friends

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
I don't disagree with this on any particular point, but just as an FYI there's a remux option in the File menu in OBS that can convert the file from any container to anything else you want, pretty much.

**Comment by reboot** [comment]
Did you ever consider that there may be reasons why the default format is FLV? It not not changed to MKV because noone had the time to changes those 2 lines. There are considerations behind some default values and submitting a change request for them without knowing the background information and discussing the reasons with someone who makes the decisions makes no sense.

**Comment by EntranceJew** [comment]
I have considered that it is possible that the reason FLV is default is for speed of writing, or that it has a lot less CPU overhead, or something to do with how RTMP works or used to work, or that it might work in the largest variety of situations, or that it could potentially produce the smallest files over-all. I have even considered that the decision was important enough to survive transitioning to the rewrite from OBS to OBS-studio.

But I have also considered that I have been privately helping people get OBS set up for their use for nearly 4 years now, and in nearly every situation I find out that they end up not knowing how to work with FLVs in their video editor, or I hear that the host they're working with does not prefer FLV at all, or comments about how YouTube would gently remind them to upload as MKV for faster processing and how they don't know how to do that. The same people that still get tripped up over which version of OBS is the correct one to download from the site, or how none of the tutorials they see look like the new OBS, or the people that are confused by stale and old information still floating around. A google search for "how to import flv in (adobe premire/imovie/sony vegas/avidemux)" brings up info from 2008-2015 of varying levels of complexity or even straight up adware. [Old questions from 2014](https://obsproject.com/forum/threads/avidemux-reads-large-obs-flv-files-wrong.20230/) show up 3rd for me, with no answer. [People have paid money](https://www.reddit.com/r/letsplay/comments/2syhil/the_flv_files_from_obs_doesnt_work_in_premiere/) to thank other people that helped them figure it out. I have also considered that the people I teach are resistant to enter Advanced mode to utilize multiple audio tracks as they are met with a big warning that says _that the default option will not work with advanced features like multiple audio tracks no matter what setting is selected_. This is not helped by the fact that remuxing causes all audio tracks to lose their names.

I have also considered that before doing all this research, the average person would not know what that option is or why it is that way. None of the other values are presented to inform you of their strengths or drawbacks, only significant warnings, they would never be inspired to change from it. The UI does not communicate the reasoning for the decisions you have made their behalf, they were never asked _why_ they are recording or what for. The setup wizard even dumps you out with FLV, even though as I have covered, nobody that would need a wizard of sorts would know what to do with a FLV when they want to edit it.

**Comment by nxtreaming** [comment]
FLV is far simple and stable than MKV. and it is very straight when you try
to save RTMP to FLV.

So, stop your stupid suggestion.


-----------------------------------------
Productive. Reliable. Fast.

**Comment by FishamanP** [comment]
Let me get this straight...
You want to change the default to MKV for BETTER video editor support?
Can I have some of what you're smoking?

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by nxtreaming** [comment]
Please do not merge this patch

MKV has no any advantage compared with FLV in the scenario of live recording.

Just think:
Your MKV file will fail to seek if your OBS has been terminated by unexpected reasons( such as power down, reboot...), but FLV is fine in this case.

FLV is simple, stable and fast.

**Comment by jp9000** [comment]
We use FLV for the default format because it's the ideal format that doesn't have a footer, so if something happens (such as the computer crashing or running out of space), the file has no risk of failure.  MKV has some protections against this, but MKV isn't a common mux option either.  If people need another format, they can easily remux via the option in the file menu.

**Pull request closed without merging**
