### PR TITLE
UI: Fix freeze when reordering filters

### PR DESCRIPTION
**Pull request by cg2121**
This seems to fix the problem where the UI would freeze when reordering filters.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
Doesn't this basically revert your prior commit?  https://github.com/cg2121/obs-studio/commit/7de289f6cc499b2591bc3390cb5f989aa8b455c6

the 'delete view' in that commit would always work before, even if view was null.

**Comment by cg2121** [comment]
This doesn't revert @reboot commit because it still checks if view exists. With this PR I don't know if the crash still happens that was fixed in #621.

**Comment by jp9000** [comment]
It does effectively revert your previous commit though.  The if statement is irrelevant because delete will do nothing if the pointer is null anyway.  That's what I meant in my second sentence.

**Pull request closed without merging**
