### PR TITLE
UI: Add exit shortcut

### PR DESCRIPTION
**Pull request by cg2121**
This adds the standard Ctrl+Q shortcut to exit.

### CODE REVIEW

**Comment by Xaymar** [comment]
Will this collide with other Hotkeys? Ctrl-Q is my mic mute/unmute key (AutoHotkey) and Ctrl-Alt-Q is my Voice Device mute/unmute key (also AutoHotkey).

**Comment by cg2121** [comment]
Ctrl+Q is the the standard way most programs can be closed.  For example, VLC can be closed this way.

**Comment by Xaymar** [comment]
In VLC it overrides my hotkey - reacts anyway even though AHK caught it. Perhaps make this configurable (Hotkeys section)? I don't think a shortcut hotkey to close OBS is something that people actually need - you might accidentally hit that while streaming MMOs and RPGS.

**Comment by cg2121** [comment]
The shortcut works only when OBS is in focus. If we had a configurable global hotkey, anytime the user would use the key, OBS would close. BTW, if the output is active, a confirmation box shows up to confirm if the users actually wants to quit or not. I will look into if I can have a global hotkey override the shortcut, so that users can have Ctrl+Q as a hotkey also.

**Comment by trwnh** [comment]
More apps I know use Ctrl+W, not Ctrl+Q. Or possibly Alt+F4.

**Comment by jp9000** [comment]
I don't think this is really all that necessary -- this isn't something that's required or particularly normal for most programs, let alone most Qt programs.  Each operating system typically has a set of system shortcut keys for closing a program.  It feels a bit strange to be adding extra exit shortcuts manually.  I'd prefer not to merge this for now unless I get some good arguments for doing so.

**Comment by WizardCM** [comment]
To expand upon Jim's response, the harder OBS is to close the better - I don't want to accidentally kill my recording/stream by hitting a key combination.

**Pull request closed without merging**
