### PR TITLE
README -> README.md | Markdown enhancement

### PR DESCRIPTION
**Pull request by RoiEXLab**
I needed a distraction from my current tasks, so I edited your README to use markdown...
Keep it or dump it. I don't care ^^

[Before](https://github.com/jp9000/obs-studio/blob/master/README) vs. [After](https://github.com/RoiEXLab/obs-studio/blob/master/README.md)

Keep up the good work!

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
see #701

**Comment by RoiEXLab** [comment]
lol ^^

**Comment by dodgepong** [comment]
Thanks for the work, but I have a hunch this won't be kept...

* https://github.com/jp9000/obs-studio/pull/292
* https://github.com/jp9000/obs-studio/pull/568
* https://github.com/jp9000/obs-studio/pull/576
* https://github.com/jp9000/obs-studio/pull/701

**Comment by jp9000** [comment]
I wouldn't mind .rst, but preferably not markdown

**Comment by RoiEXLab** [comment]
@jp9000 I still don't get why you prefer raw text over markdown, but whatever :D
I will delete my branch then...

**Comment by jp9000** [comment]
There's not really "something wrong with" markdown per se, but it's mostly just preference.  Markdown just isn't quite as clean when you're looking at it in raw text form.  RST would probably be the best compromise for me personally.

**Comment by RoiEXLab** [comment]
If it's just about the raw text for, is this better?

**Comment by jp9000** [comment]
As I said, I don't want to change the file to markdown at all.

**Comment by RoiEXLab** [comment]
No problem then...

**Pull request closed without merging**
