### PR TITLE
added Facebook Live as a service

### PR DESCRIPTION
**Pull request by CallumHoward**

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
Out of curiosity, where did you get those max bitrate and keyframe interval values?

**Comment by CallumHoward** [comment]
Hi jp9000, values from [here](https://developers.facebook.com/docs/videos/live-video-api#recommendations), as well as advice from a Facebook software engineer.

**Comment by jp9000** [comment]
At the bottom of the page it says 2500 max bitrate, and 2-sec keyframe interval, though in the file you put 2000 max bitrate and 1-sec keyframe interval.

Was that intentional?  Just double-checking.

**Comment by CallumHoward** [comment]
Those figures were advised to me to achieve more stable performance than the minimum requirements. I have tested both, sets of values and they both seem to perform fine.

**Comment by jp9000** [comment]
Alright then, going to change the commit title and merge.

**Pull request closed without merging**
