### PR TITLE
obs-outputs: Compatible with RTMPS using OpenSSL

### PR DESCRIPTION
**Pull request by yogpstop**

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
Mind if SSL is disabled by default?  I don't want it enabled by default.  Have you tested this code?  I have no way of testing this currently.

**Comment by yogpstop** [comment]
Thank you for reviewing.
OK. I'll update this pull request with SSL option (disabled default).
I tested this code only in Windows 7 VS2013 64bit. But I can test it in other some platforms. (win 32bit, linux(gentoo) 64bit) I'll test in these environments. However I can't test in Macintosh.
But I'm sorry. I'm busy this weekend. So it takes 3 or 4 days.

**Comment by jp9000** [comment]
What I mean is have you tested this with both RTMPS and RTMP servers to verify that they both function properly even despite being compiled with SSL support?  A lot of the code paths change when NO_CRYPTO isn't set.

**Comment by yogpstop** [comment]
oh, sorry.
I tested on original Red5 RTMPS server and unknown RTMP server(japanese live streaming site, may be using official adobe media server) with SSL enabled. It works correctly.

**Comment by yogpstop** [comment]
Sorry for late updating.
I added SSL option.
And I built on both VC2013_64 and VC2013_32.
And I can publish to both RTMP and RTMPS server.
I don't test on linux yet, sorry.

**Pull request closed without merging**
