### PR TITLE
UI: added separate icons for recording and streaming

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by SuslikV** [comment]
In OBS Studio you can stream and record simultaneously. Whether this patch able to add a second icon to the tray (rec+stream=two icons) or no?

**Comment by TotalCaesar659** [comment]
@SuslikV , I've forgot about that. I'll try to do that later with one more icon - it's too much with 2 icons in the tray, I guess.

**Comment by Xaymar** [comment]
Not a personal favourite of mine, I much prefer the small red circle that OBSs tray icon shows when recording.

Perhaps change this so that there are two circles, one for streaming (bottom left) and one for recording (bottom right). The streaming one would still be red, while the recording one would be blue/green/yellow/orange.

**Comment by SuslikV** [comment]
I have thread where I posted my icon examples: https://obsproject.com/forum/threads/new-main-icon-color.41567/#post-187695

As for code changes, I think, it is good option to change ALL icons you have when you change application theme. A lot of work there...

As for now, Studio uses fixed size icons and the simplest QT mechanism to scale them down. Small pictures usually require simple drawing (less detail) and higher contrast. So, amateur artist (like me:) prefer to replace or redraw the small image rather than scale it down for small icons.

**Comment by TotalCaesar659** [comment]
@SuslikV , great icons, but maybe it's better to create a separate OBS theme with same cyan colors for these icons? For one united style.
@Xaymar , I wanted to make the icons more informative. Unlike simple circles, text explains the OBS state and creates association that is easier for understanding. Of course I don't expect that everyone will like it, tastes are different, but it's not bad to propose something new.
It would be good to create poll on the forum or something for this.

**Comment by jp9000** [comment]
Very nice icons.  I was almost expecting two dots instead of one dot.  Only design flaw with it at the moment is that it'll exclusively use the first icon that you use, rather than accommodate both.  If you turn on the stream, then turn on the recording, then turn off the stream, it'll still use the "live" icon.

But unfortunately, as nice as the icons are, I'm not sure if they're actually necessarily.  You don't really need to be able to differentiate whether you're live or whether you're streaming via the tray.  It feels like the old dot is more than sufficient to know that something is active.  Maybe I'm wrong or someone might disagree, but I really think this whole thing is a bit superfluous.

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
Unfortunately, although the icons are nice, as stated in my previous message, it cannot show both streaming and recording, it can only show one or the other, which can cause confusion to the user as to what it's currently doing.  Additionally, if you turn streaming on, then turn recording on, then turn streaming off, it'll still have the streaming icon.  So I've decided for now to respectfully decline this as I don't feel comfortable with it's actual inability to show both streaming/recording, and the possibility that it may miscommunicate its current state to the user.

**Pull request closed without merging**
