### PR TITLE
decklink: Add option to select channel format

### PR DESCRIPTION
**Pull request by mntone**
This is a workaround for:
https://obsproject.com/mantis/view.php?id=837

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
I've tested these changes locally, and they introduce a inconsistent audio delay (tested against 18.0.1 release), as well as a crash when trying to change channel settings or exit OBS at line 112 of audio-repack.c.

The delay seems to happen randomly, only when buffering is enabled, and I'm only able to replicate about 1/10 times launching so I'm not sure what's causing it.

The crash is able to be replicated every time I either exit OBS, or try to change the audio channel settings in the Blackmagic Device Source properties.

**Comment by mntone** [comment]
Thank you for your report.

The crash is fixed in latest commit of my repository. I will apply commit to PR.

I confirmed the delay, but I'm not sure what's causing it, too. I examine this phenomenon.

**Comment by mntone** [comment]
I pushed the commit for multi channel audio.

I continue to examine the delay, however, I will create new PR for the delay, and you evaluate this PR and merge.

**Comment by Fenrirthviti** [comment]
Thank you for the update, I was able to test the new version and everything is working properly now. I was also able to replicate the audio delay issue in 18.0.1 release, so that is unrelated to these changes.

Thank you for your quick responses!

**Comment by jp9000** [comment]
Fixing some whitespace issues, then manually merging.  Thank you for the fix!

**Pull request closed without merging**
