### PR TITLE
UI: Add Multiview projector support

### PR DESCRIPTION
**Pull request by admshao**
**THIS IS A CALL FOR FEEDBACK**

This allow a better view of your scenes by getting up to the first 8 ones and compose them in a single view.

Enable Studio Mode and the option will show in the context menu. The source selected for Preview will show with a green box while a red one will display on the Program.

Expect some increase in GPU usage when in multiview and optimization patches are very welcomed as well as UI related patches.

Stuff to work on:

- Live update changes in scenes in main OBS (Right now will CRASH)
- Add per scene audio indicators
- Draw bigger lines around sources/better spacing
- Better way to handle background color for source names (proper math)
- Add Scene selector/Drag n Drop(?)
- ????

Suggestions please!

This was tested on Linux(arch, gnome 3.26, K 4.13) and Windows 10(CFU). I have no Mac =(

vlcsnap-2017-11-05-19h42m56s914

vlcsnap-2017-11-05-19h44m53s649

### CODE REVIEW

**Comment by derrod** [comment]
One thing I noticed while checking it out is that source names and order do not update in the multiview at the moment. That might be one area for improvement.

**Comment by WizardCM** [comment]
This is looking really good already. Alongside the borders (which I agree should be thicker), I really feel there should be actual spacing between each preview too, right now it really feels like a weird mashup.

I agree with what you said in IRC, that there should be some kind of selector, maybe something very similar to the "Choose Existing" menu but for scenes. Maybe a context/right click menu which has the following options: 

```
|-------------------------|
| Modify this scene slot  |   Show a "Choose Existing" menu for scenes
| Add a new scene slot    |   
| Remove this scene slot  |
|-------------------------|
```

Combine this with an ability to drag scenes to reorder them (with similar drag-and-drop behaviour to the modular UI, and it should be super intuitive. Though this'd be a bonus because usually people have their scenes in a very specific order already.

**Comment by jp9000** [comment]
Shaolin when you have a chance come by chat again.  I want to modify your branch a bit and want to discuss and update your repository.  I fixed up a number of things -- fixed the bugs, crashes, modified some of the design, removed the magic numbers, just generally a lot of refactoring.  I really like this feature so I want to see it get merged, though yea, the details on how users can use it might need a bit more ironing out later.  Still, I think it's actually pretty good as-is even displaying the first 8 scenes, we can probably work out on how to whitelist/blacklist scenes from the multiview later if you want.

**Comment by enzanki-ars** [comment]
Just adding my two cents here:

I would absolutely love to see this feature.  I have been manually emulating it as close as possible using either:
- an extra scene with all of the scenes and using preview windows
- a bunch of preview windows

Clearly, neither of these are a great option.  

-----

One note I will add:

I have an interesting method of setting up my scenes:

As seen below, 3 types of scenes:
* Base: These are either the background scenes or the overlay scenes
* Input: These are all of the inputs, with any backgrounds added in (just incase the input is not 16:9 or the input goes offline)
* Main: These are the actual scenes I use when switching.  It usually ends up looking like:
  * Background
  * Inputs
  * Overlays

(Sidenote: it would be neat for a folder like feature to organize the scenes.  I will look for/submit a feature request soon.  Keep forgetting....)

image

As you can see, that is a lot of scenes.  If this feature were to be added, the ability to select which scenes are displayed would be greatly appreciated.

**Comment by SuslikV** [comment]
I think, of this option in different way. What the sense to preview only and not to switch scenes by single click?

I think, in Studio Mode or not, it should update the output, always. If it could be implemented as one of the Tools feature... with its own interactive window, with options by right-click menu over any of this previews inside this new window (for example layout switch: 2x2, 3x3, 4x4; reserve the cell for live{program} window; per scene transitions change) and with per scene switch hotkeys label reminder. Maybe it is hard to implement and it looks like "Pro" feature, but who knows...

**Comment by jp9000** [comment]
Someone else suggested being able to click it.  It's definitely possible to do but a real pain for now.

**Pull request closed without merging**
