### PR TITLE
Update, rename and improve README & CONTRIBUTING markdown files

### PR DESCRIPTION
**Pull request by patrickemuller**

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by reboot** [comment]
Jim said in an earlier pull request he wants the files to remain normal plain text: https://github.com/jp9000/obs-studio/pull/568#issuecomment-233330846

**Comment by jp9000** [comment]
I'm terribly sorry that you went to the work of converting this to markdown, though we prefer to use plain text.

**Comment by patrickemuller** [comment]
I don't want to be rude but...plain text is horrible, unprofessional and terrible to read.
It's not just about be markdown, it's about to look good and pass confidence that this is a serious project and not a forgotten one like many other projects on Github

**Comment by Chiitoo** [comment]
I, for one, want to thank jp9000 for this decision.  I prefer plain text myself, but I do understand it doesn't please everybody.  :]

I don't see how it would make the project look less serious or professional, however, but that's me.  ^^

**Comment by Spekular** [comment]
@patrickemuller the readme needs to be readable outside of github as well. Markdown isn't good for that.

**Pull request closed without merging**
