### PR TITLE
Updated the Blackmagic SDK to 10.8.0

### PR DESCRIPTION
**Pull request by c3r1c3**
Updated to help support the newest cards, features, bug fixes, and options.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by c3r1c3** [comment]
They came from BMD... but I could remove them manually.

**Comment by nobme** [comment]
Hi. Will this be committed soon? Waiting on BMD sdk update.

**Comment by c3r1c3** [comment]
nobme: What are you waiting for that the updated SDK fixes?

**Comment by nobme** [comment]
I have trouble With using OBS against a New BMD Television Studio. It seems so the New SDK(v.10.8) will fix this issue.

**Pull request closed without merging**
