### PR TITLE
CI: fix curl download if file doesn't exist

### PR DESCRIPTION
**Pull request by craftwar**
I don't know how to write cmd if statement in appveyor.yml. I write in another file.

### CODE REVIEW

**Comment by RytoEX** [comment]
Hi!  I'm a bit confused by this PR, since it seems to mostly revert back to the behavior before PR #919, minus the `-z` option of `curl`.  Has there been a failure on AppVeyor recently that this PR would solve?  This PR also fails to build on AppVeyor.  I _think_ this is because of the return output of `curl` being an error code.  The `if` statement checks in `CI/download-deps.cmd` looks for the existence of a file named `filename.txt`.

To do this in `appveyor.yml` without a separate script file, I think that this will work (keep indentation levels in mind):
```
  - if exist dependencies2015.zip (curl -kLO https://obsproject.com/downloads/dependencies2015.zip -f --retry 5 -z dependencies2015.zip) else (curl -kLO https://obsproject.com/downloads/dependencies2015.zip -f --retry 5 -C -)
  - if exist vlc.zip (curl -kLO https://obsproject.com/downloads/vlc.zip -f --retry 5 -z vlc.zip) else (curl -kLO https://obsproject.com/downloads/vlc.zip -f --retry 5 -C -)
```

If you want it formatted with whitespace:
```
  - if exist dependencies2015.zip (
      curl -kLO https://obsproject.com/downloads/dependencies2015.zip -f --retry 5 -z dependencies2015.zip
    ) else (
      curl -kLO https://obsproject.com/downloads/dependencies2015.zip -f --retry 5 -C -
    )
  - if exist vlc.zip (
      curl -kLO https://obsproject.com/downloads/vlc.zip -f --retry 5 -z vlc.zip
    ) else (
      curl -kLO https://obsproject.com/downloads/vlc.zip -f --retry 5 -C -
    )
```

The `appveyor.yml` file uses Windows Batch syntax for commands by default or PowerShell if specified.

**Comment by craftwar** [comment]
I find if file doesn't exist it will fail. (no file to compare) Use old behavior if file doesn't exist.
I did try to add in .yml but fail. I don't know the syntax yml use. 
Curl fails sometimes, it's not related to my changes. Maybe, we should find a more reliable way to download file.

My build is successful.
https://ci.appveyor.com/project/craftwar_appveyor/obs-studio/build/172

**Comment by craftwar** [comment]
@RytoEX nice, it works.
Another question, do we prefer all scripts in yml or separate some functions into file. (like obs-studio\CI\before-deploy-win.cmd)

I don't understand why three move are required. (maybe an old hack?) I can use VS2017 build successfully without them on PC and appveyor.
But don't upgrade appveyor to VS2017. (No Qt 32bit binary on appveyor VS2017 image)

**Comment by RytoEX** [comment]
> I find if file doesn't exist it will fail.

That's strange.  In my local tests with `curl`, it would issue a warning and then download the file anyway.  I'm not sure if it's handled differently on AppVeyor.

> Curl fails sometimes, it's not related to my changes.

I'd guess that it's caused when `curl` tries to resume downloading against a completed file.  In this case, `curl` receives an HTTP 416 code and then gives a return code of 22, which is regarded as an error.

As for questions about the design and structure of the CI services used for OBS Studio, @DDRBoxman and @Gol-D-Ace set up most of this, so they would probably be the best people to ask.

**Comment by jp9000** [comment]
I'm confused, and I don't think this is necessary.  We don't really have trouble with curl with our builds.

**Comment by craftwar** [comment]
I remember why I create this now. If someone fork this repo, he will get error when using appveyor. This may happen when appveyor cache dispears accidentally too. Looks like it's bugged, can't be updated. I will create new PR.

**Pull request closed without merging**
