### PR TITLE
rtmp-services: Add Nood as a service

### PR DESCRIPTION
**Pull request by jumoog**
Nood is a Live video streaming platform and community for adults
see: https://www.nood.tv

We are still in beta but we already using obs-studio :+1: 

Thanks for obs-studio :tada:

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
Thank you, though please remove the "common" json item.  Your service is a bit too new and I'd prefer not to have it in the list and basically be advertised to users.  I know it's annoying to have to deal with this, and I'll figure out a better way to deal with it in the future, but for now this is just how we have to handle it.

**Comment by jumoog** [comment]
done :+1:

**Comment by jp9000** [comment]
Thank you!

**Comment by jp9000** [comment]
Er!  Meant to merge this.

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Pull request merged**
