### PR TITLE
UI: Add option to stop output after specified time

### PR DESCRIPTION
**Pull request by cg2121**
This adds an optional timer to the streaming and recording outputs. After this time is elapsed the outputs are stopped.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by WizardCM** [comment]
Oooh, this would be perfect for recording Overwatch highlights - auto-stop at 16 seconds. :D

**Comment by jp9000** [comment]
I think that rather than be in the advanced section and part of the main UI, this should be a tool in the tools menu, added in UI\frontend-plugins\frontend-tools.  I feel this feature should be something that shouldn't be in the main settings or part of the main UI.

As you have it programmed now, it will make it so the stream will always turn off after a specific amount every single time.  I think that most people will probably not want that, most will probably just want it as a one-time thing that they want to use for specific situations, hence why it'd be more ideal as a tool.

The tool window should be programmed to be non-modal and have the countdown timer in it.

Think you can do that for me?

**Comment by cg2121** [comment]
I will see what I can do.

**Comment by jp9000** [comment]
Thanks.  I'll close this for now then just so I can clear up the pull requests.  Re-open when you feel necessary.

The tool window should probably be super simple -- a small non-modal dialog with a timer label that shows the time counting down, an integer scroller widget with the seconds (or maybe minutes would be better?), and a button that can probably both start and cancel the shutdown timer.  I feel like that would probably be ideal, and can be extended later.  Probably doesn't even need to save settings.

Hm, I really need to help with the python plugin to make these little tools easier to implement.

**Pull request closed without merging**
