### PR TITLE
Update services.json

### PR DESCRIPTION
**Pull request by notmark**
Removed LAX server, added new NYC server for Vaughn Live & Breakers.TV

### CODE REVIEW

**Comment by RytoEX** [comment]
PRs #932 and #933 should be one PR with a single commit.  See these examples of similar PRs:

- https://github.com/jp9000/obs-studio/pull/927
- https://github.com/jp9000/obs-studio/pull/901
- https://github.com/jp9000/obs-studio/pull/866
- https://github.com/jp9000/obs-studio/pull/692

Or use this search filter on the "[Pull requests](https://github.com/jp9000/obs-studio/pulls)" tab:
`is:pr is:closed rtmp-services`

It may also be helpful if you pointed to documentation that verifies this change.

---

Further food for thought, though not directly related to #932 or #933...  Why _are_ there two separate entries for "Vaughn Live / iNSTAGIB" and "Breakers.TV" that have identical ingests and recommended settings?  Would merging them cause disruption with existing user settings?

**Comment by notmark** [comment]
I'm half asleep and quite frankly forgot about the version change until after I submitted the first request. Sorry!

As for the reason of separation: Breakers.TV may soon be sold and no longer a part of VaughnSoft. Also it would mess with existing user settings like you said.

**Comment by jp9000** [comment]
If possible edit this PR to have the packages modification, then remove the packages PR.

**Comment by mercenaryship** [comment]
We need to be knowing how to make an egg sandwich.

ALL RIGHTS RESERVED

**Comment by jp9000** [comment]
Fixing this commit up.  Your commit message doesn't follow the guidelines, and you didn't combine/squash this with the services.json pull request you made.  I'll fix it up, but if possible please try to avoid that in the future.

Merging with those changes shortly.

**Pull request closed without merging**
