### PR TITLE
UI: Add direct to preview in studio mode

### PR DESCRIPTION
**Pull request by cg2121**
This adds the ability to have the scene go directly to preview when double clicked when in studio mode.

### CODE REVIEW

**Comment by RytoEX** [comment]
Do you mean directly to preview with no transition, or does it change the Program scene (the live scene, the one that's broadcasting/recording) with the intended transition?  I don't have time to build right now, or I'd test myself, so I thought I'd ask here.

**Comment by cg2121** [comment]
This would just like if you hit the transition button, except this makes it do it automatically.

**Comment by RytoEX** [comment]
So it makes the scene go to the _Program_ view, not the Preview?

**Comment by cg2121** [comment]
Once you double click the scene in the list, it goes to the program (on the left), then automatically transitions to the preview (on the right).

**Comment by dodgepong** [comment]
The window on the right (the actual live view) is referred to as Program, the window showing the scene that is "queued up" (on the left) is referred to as Preview.

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
I changed this to be an option in general settings rather than the default behavior just in case the user doesn't want/expect this behavior.  I'm leaving it off by default for now just because I don't want to alert the current functionality and change functionality unexpectedly, but I might make it default to on in the future.

Merging shortly -- you'll see "closed in [commit hash]".

**Pull request closed without merging**
