### PR TITLE
Build on travis and appveyor

### PR DESCRIPTION
**Pull request by DDRBoxman**
This allows automatic building on Linux, OSX, and Windows when new commits are added and pull requests are made.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by DDRBoxman** [comment]
I'd like to investigate code style checking tools that could be run on PRs too.

**Comment by dodgepong** [comment]
This seems a bit forward, given that OBS itself does not use Travis or AppVeyor. If you want to use them for your own builds, surely you can just keep the configs on your own? Or are you suggesting that OBS *should* use Travis/AppVeyor?

OBS has a Jenkins server, though it's currently inactive, and I am generally in favor of nightly builds...I guess I just feel like this is the sort of thing that should be discussed more directly with Jim first. You can find him in the OBS dev chat room, #obs-dev on Quakenet.

**Comment by DDRBoxman** [comment]
My intent here was for OBS to leverage these services to do basic sanity checking of PRs. Make sure the code compiles across all platforms, run any unit tests, and do any other checks that could be automated.

They're free for open source and lots of open source contributors are used to working with them.

I actually hadn't considered using them for actually distributing the artifacts since the current system seems to work okay.

**Comment by jp9000** [comment]
Thank you, although we're not currently using travis/appveyor.  Perhaps in the future if we decide to use those I'd be willing to add it in, but for now it feels somewhat unneeded.

**Pull request closed without merging**
