### PR TITLE
UI: Add reset button to transformation dialog

### PR DESCRIPTION
**Pull request by cg2121**
This adds a reset button to the transform dialog.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by sajiaghias6** [comment]
I money doller bill banko deniero mula

**Comment by reboot** [comment]
Maybe it would be good to add a close/cancel button too. I already hit the reset button multiple times by accident when i wanted to close the dialog. Once a dialog has buttons, you kind of expect it to have a close, ok or cancel button, because that is just standard for dialogs.

**Comment by cg2121** [comment]
I have now added a OK button that closes the dialog, and added a confirmation dialog when the reset button is clicked.

**Comment by reboot** [comment]
I would put the OK button to the right, so that the default buttons that dismiss a dialog are in the usual position. But i know that the Apply button in the settings is also not placed like this. So maybe someone else should decide that makes more sense.

**Comment by cg2121** [comment]
I have now reordered the reset and ok buttons.

**Comment by reboot** [comment]
After looking through some other UI code I think it would be the best to use a QDialogButtonBox for the buttons instead of making a custom horizontal QGridLayout. QDialogButtonBox also makes sure the buttons are placed and ordered consistently in all dialogs.

**Comment by cg2121** [comment]
I have now changed it to use QDialogButtonBox.

**Pull request closed without merging**
