### PR TITLE
UI: Add option to minimize to system tray

### PR DESCRIPTION
**Pull request by cg2121**
This adds an option to minimize to system tray when OBS is started.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by reboot** [comment]
I think the option is misslabeled. It does not only minimize to tray on start, it activates the tray icon at all. Minimize to tray on start should probably be an additional option. It should be possible to activate the tray icon without OBS starting minimized.

It would also be nice if you didn't have to restart OBS to activate the tray icon.

**Comment by cg2121** [comment]
I have now added the option to start the system tray icon when the app is running.

**Comment by reboot** [comment]
If you only enable "Enable system tray icon" without the "Minimize to system try when started" option the menu of the icon is wrong after you start OBS. It has a "Show" entry, but the window is already visible.

Also i would disable the minimize option entry when the system tray option is not enabled, like the automatic recording options. The second option only makes sense when the first option is enabled.

Maybe it would also be a good idea to automatically disable the preview when the window is hidden. There is no need to make the video thread render the image, when you can't see it.

You also need to check your code style.

**Comment by reboot** [comment]
Another thing, if you close OBS using the exit menu entry then the window position is lost and the window is not placed at the original position on the next start. You should probably rebase your commit on the current master branch, because this code has changed.

**Comment by cg2121** [comment]
I'm still fairly new to github, so I dont quite understand how the merging of remote tracking branches work. I will submit a new pull request when I figure everything out.

**Comment by reboot** [comment]
In my opinion it is better to keep the pull request open, to keep the history. You can always update it by push something new to your branch.

**Pull request closed without merging**
