### PR TITLE
libobs: log which source causes audio buffering

### PR DESCRIPTION
**Pull request by Palakis**
As an OBS Studio and maintainer of a source plugin (obs-ndi), myself or others frequently run into the issue of audio desync. This is generally caused by a source that sends audio frames with wrong or too late timestamps, and finding out which source(s) cause this relies on trial and error.

This Pull Request aims to facilitate this. Whenever audio buffering is going to be increased, it logs which source causes buffering before logging the `adding x milliseconds of audio buffering` message.

Example:
```
16:07:58.469: audio from source 'BACKGROUND VIDEO' is late
16:07:58.470: adding 170 milliseconds of audio buffering, total audio buffering is now 170 milliseconds
```

It should be good to mention that this won't log every late source at once, but only the one that cause a specific occurence of audio buffering.

**Tasks :**
- [X] Log message
- [x] Show current audio buffering duration in the Stats window

### CODE REVIEW

**Comment by SuslikV** [comment]
The string
`late. buffering` - either:
 `late, buffering` or 
`late - buffering` or 
`late. Buffering` or 
`late (buffering`

**Comment by Palakis** [comment]
Fixed the merge conflict.

**Comment by chinasarft** [comment]
is this "adding x milliseconds of audio buffering" lead to desync?
when i streaming(rtmp), this is desync and sometimes audio will disapeared.
and more, desync is up to 20 second
yeah, there is adding x milliseconds of audio buffering in the log file.
in my case, all souce are media source

**Comment by jp9000** [comment]
Audio buffering does not lead to desync.  Audio buffering is completely normal.  I actually do not see a purpose for this pull request.  If you are having desync, it is not caused by audio buffering.  Audio buffering just simply adds latency -- nothing more.  It does not alter or impact sync.

**Comment by Palakis** [comment]
@jp9000 
"If you are having desync, it is not caused by audio buffering. Audio buffering just simply adds latency -- nothing more. It does not alter or impact sync."

My bad, I used wrong wording.
By "desync" I don't mean phase desync of the timing values, but rather audio/video relative delay.

Many users of the previous version of obs-ndi have reported that they encounter a quick or moderately quick build-up of A/V relative delay. The NDI source was sending late timestamps, which cause additional audio buffering, up to the point of reaching the maximum allowed audio buffering of around 960 ms.
But this was a pain to diagnose each individual case because other async sources (media sources, WASAPI, ...) can cause additional audio buffering, which causes additional A/V relative delay.

This wouldn't be much of a trouble if OBS compensated the additional audio buffering with additional video buffering (hypothetically speaking just as an example, not an actual suggestion), because lips or other video content synced to audio would be kept in sync with each other (no relative A/V delay).

**Comment by chinasarft** [comment]
@jp9000 
19.0.3 and 20.1.3 i tested
my case: one scene, 6 media souce, in studio mode and very awful network environment
when I streaming, i encountered a/v not sync. video ahead of audio up to about 20s(is the max), even if I update the media source which not sync
and sometimes voice will dispeared, but update will recover
I not found why.

**Comment by Palakis** [comment]
@jp9000 Following up on our Discord chat yesterday, I've added a "late async audio source" (didn't come with a better name) that sends audio frames 1 second in the past (os_gettime_ns() minus 1 second). This instantly maxes out audio buffering. When tested with media sources or capture devices loaded, it causes noticeable A/V desync.

Most sync tests videos have a 1 second interval between ticks. As the maximum possible A/V desync is 960 ms, 1 second ticks don't show noticeable desync. I've made a test sequence with ticks spaced at 2-second intervals.
The video on YouTube : https://youtu.be/hUbM_qhsTd8
Ready to download : https://transfer.sh/bKN1e/1080p60%20sync%20test%20-%202-second%20interval.mp4

Steps to reproduce:
- Start OBS with a clean scene collection.
- Start a stream or recording (in order to the see and hear if there's an A/V desync)
- Load the sync test video as a Media Source to the current scene
- Have a look at "Audio buffering" in the stats window. Should be under 200 ms.
- On the output, the sync test video source should show the test card in the sync with the 1 kHz beep
- Add a "Late Async Audio Source (causes audio buffering)" to the current scene
- Have a look at "Audio buffering" in the stats window. Should be at 960 ms, the maximum possible
- Look at the output : the test card image and beep are not synced anymore. Some audio drops are also audible, but these are normal and expected.
- Remove the "Late Async Audio Source"
- Look at the output again : audio stopped dropping, but the desync is still there, and audio buffering is still at 960 ms.

**Comment by jp9000** [comment]
In the recording I'm not getting any issues from the media source when using your replications steps, so I'm rather confused.

Furthermore, I wrote another test for audio buffering here in addition to this, which has both video/audio:  https://github.com/jp9000/obs-studio/commit/dd8cf409d0f35253813b3dd4d5e2bfa5ecc31fc2 -- it artificially induces approximately 750 milliseconds of audio buffering and instead of an on/off cycle, it uses 7 frequency cycles to ensure that audio/video are in the right place with no chance of any sort of placebo scenario.  That test was also successful and there were no playback issues there.

**Comment by jp9000** [comment]
I think there must be some sort of communication breakdown going on because there's nothing here affecting audio sync, yet the word "sync" keeps being used here.  Are you sure that you're using the right wording here?  Buffering does not affect audio/video sync from any testing that I've done as of yet, including the steps you listed.  It can happen in response to something going going out of sync if the audio timestamps are bad for example and audio timing goes below video timing on a source or something, but the buffering itself is not and cannot be the cause of sync issues -- as of yet from my testing.

**Comment by Palakis** [comment]
Closing this, as the desync issue doesn't appear in stream and recording output. These work perfectly fine.
My test setup was faulty, as I used the NDI output from obs-ndi, which isn't my greatest piece of engineering.
I got biaised. I owe deep apologies to Jim.

**Pull request closed without merging**
