### PR TITLE
Add the ability to specify a custom ALSA PCM

### PR DESCRIPTION
**Pull request by Enzime**
Adds a custom 'device' listed as `Custom` which shows a new text field allowing entry of a PCM name.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by robske110** [comment]
@ONSBalder are you a bot?

**Comment by jumoog** [comment]
yes he is

**Comment by robske110** [comment]
lol are bots allowed @Github?

**Comment by jumoog** [comment]
lol ofc

**Comment by jp9000** [comment]
Please avoid commenting on a PR unless it's about the PR.

Could you please specify why you need this?  What case does it solve?  All devices should be listed by default in ALSA.

**Comment by Enzime** [comment]
By default, accessing a HW device in ALSA will require exclusive access to that device, e.g. microphone. To get around this ALSA has `http://alsa.opensrc.org/Dsnoop` which will not show up as a hardware device, because it is a custom pcm, and allowing someone to specify a pcm, any PCMs they specify inside `.asoundrc` will be usable from obs.

An example PCM that I have in my `.asoundrc` which allows me to play audio that I want to record to both my loopback and speakers, and any recording that goes to that pcm will automatically go through the `dsnoop` ALSA module.

```
pcm.record {
	type asym
	playback.pcm "plug:both"
	capture.pcm "dsnoop:Loopback,1,0"
}
```

**Comment by Chiitoo** [comment]
Indeed, this would be a very welcome change.

I briefly touched upon this in [Linux] ALSA Input Plugin #494, but I didn't seem to make it clear that it would be best to have all the PCMs listed.  As it is, one needs to configure their 'default' device to be the one doing the magic (to use a Loopback device for example).

If a device isn't capable of doing hardware mixing, it's almost never useful to use them directly.  Without 'dmix', for example, as mentioned before me, an application will hog the device to itself.

Thanks!

**Pull request closed without merging**
