### PR TITLE
rtmp-services: update Hitbox ingest list

### PR DESCRIPTION
**Pull request by Radzaquiel**
Modify: EU-North (London) => EU-West (London)
Add: EU-North (Amsterdam)

### CODE REVIEW

**Comment by Gol-D-Ace** [comment]
You missed the package.json

**Comment by Radzaquiel** [comment]
oh that's new...do I just need to increase the version number then ?

**Comment by Gol-D-Ace** [comment]
Yes both the numbers.

**Comment by Gol-D-Ace** [comment]
but not format_version

**Comment by Gol-D-Ace** [comment]
you should squash this commits and then force push to your repo.

**Comment by Gol-D-Ace** [comment]
I squashed your commits @Radzaquiel

**Pull request closed without merging**
