### PR TITLE
Obs qsv11

### PR DESCRIPTION
**Pull request by chinhseoul**

### CODE REVIEW

**Comment by dodgepong** [comment]
Is there a reason you are submitting this PR? This branch has existed in the OBS repo for a while now, and if it was ready, it would have been merged. You yourself didn't add any code here. I don't see the point of this.

**Comment by seung-woo** [comment]
I will double check with Jim to see why it hasn't been merged yet.

**Comment by chinhseoul** [comment]
ok ?

**Comment by chinhseoul** [comment]
tôi cần ban cho tôi biết lỗi cụ thể ? {Tôi không nhìn thấy điểm này.}?????

**Comment by jp9000** [comment]
Hi chinhseoul, we already have this on a branch, please don't pull request existing branches.  I'm going to close the pull request because it's already existing on a branch.

There hasn't been much development on the branch at the moment due to the fact that 1.) I don't have a QSV-capable CPU, so I myself can't contribute to it yet, I've had to wait on others to do that, and 2.) I've been waiting for backward compatibility with older 2xxx model CPUs.

I will acquire a QSV-capable CPU so I can help on this, I was already intending to do so for 0.14.0 if someone else didn't before me.

**Pull request closed without merging**
