### PR TITLE
Inital pass at adding a color source plugin

### PR DESCRIPTION
**Pull request by DDRBoxman**
I thought I'd throw together a quick color source plugin for backdrops etc.

Currently, I'm having issues actually rendering in the OBS main window, it seems to render in the settings window fine though.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
Did you close this because you had accidentally disabled the syphon plugin?  You don't need to close pull requests when you make a mistake.  You can just rebase/amend and then just force push your fork's branch to automatically update the pull request.

**Comment by DDRBoxman** [comment]
I was actually going to spend some more time digging into the graphics API to actually implement this correctly.

**Comment by jp9000** [comment]
Ah okay, no problem, take your time.  Feel free to contact me any time if you have any questions about it.

**Pull request closed without merging**
