### PR TITLE
rtmp-services: Add AfreecaTV streaming service

### PR DESCRIPTION
**Pull request by rpslack**

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by rpslack** [comment]
i can't merge #613, #614 . someone merge request.

**Comment by Gol-D-Ace** [comment]
@rpslack We usually don't have multiple services just for multiple regions. Is it ok when I merge all addresses to just one service?

**Comment by Gol-D-Ace** [comment]
I just amended your commit.
This is not possible through the GitHub Website.

https://www.atlassian.com/git/tutorials/rewriting-history/

**Pull request closed without merging**
