### PR TITLE
UI: Add ability to copy-paste scene item transforms

### PR DESCRIPTION
**Pull request by RytoEX**
This is something I'd seen a few users ask about.

This commit adds the ability to copy a scene item's transform and crop settings and paste those settings onto another scene item in any scene or scene collection. It also changes the menu shortcut key for the Transform action "Center to screen" from "C" to "n" because "C" is the standard shortcut key for "Copy" in most other applications.

I was hesitant to change the shortcut key for "Center to screen", but having "C" for "Copy transform" makes too much sense to me, so the best option was to change it despite my initial misgivings, in my opinion.

The functions on_actionCopyTransform_triggered and on_actionPasteTransform_triggered were adapted from on_actionResetTransform_triggered.  It just now occurred to me that there is a function [GetCurrentSceneItem](https://github.com/jp9000/obs-studio/blob/master/UI/window-basic-main.cpp#L1580).  I'm not sure if it would have been better to use that rather than obs_scene_enum_items.  If it is, I'll gladly change the code and amend the commits.  If obs_scene_enum_items is correct, I'd love to know why.

I've compiled and tested this on Windows 10 Pro 64-bit Version 1607 (OS Build 14393.447).  The functionality seemed to work fine for me, but I would welcome additional testing.  As always, reviews, suggestions, and edits are welcome.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by ThoNohT** [comment]
I would think that Ctrl+ C copies the scene item, not just the transform. I'm not sure replacing the center shortcut for this is such a good idea, especially for functionality that is not entirely intuitive.

**Comment by RytoEX** [comment]
@ThoNohT This doesn't create or replace the Control+C shortcut.  It just replaced the menu shortcut key, so that if you have the transform menu itself opened, you can press "c" to select and activate the "Copy Transform" option.

**Comment by ThoNohT** [comment]
Ctrl + C is the center hotkey in OBS1, my bad, I thought that never changed. In OBS Studio it is Ctrl + D apparently. It's probably not that bad then. Though the discrepancy between n/c and Ctrl + D is still a bit weird, that's not the issue of this PR.

**Comment by SuslikV** [comment]
What obs is really lacks - is the exact values after cropping. Like, "Cropped to: Width x Height" label in Transform and in 'Crop' filter. I think it is unhandy to use mental arithmetic each time when you need to keep aspect ratio or fit the size. You even don't know is the source already fits the base canvas (or other size) or it  is still left 1-2 pixels... At least, 'Size' is available.

**Comment by RytoEX** [comment]
@SuslikV 
Displaying the exact size/dimensions of a source after cropping is something that could be displayed in the Transform window, but it is not the focus of this PR.  I'm pretty sure I could whip up a patch for that (displaying a read-only copy of the source's cropped size), though I'm not fully clear on exactly what purpose it would serve.

I do not think that you need to display the source's transform info in the main OBS UI.  In fact, you can leave the Transform window open while you move the source around or adjust its size/crop settings and see the values change.

**Comment by SuslikV** [comment]
And I didn't see purpose to implement "transform copy" to the application that wasn't designed to create complex scenes at all - it hasn't axis restraints (horizontal, vertical, angle, grid snapping), it hasn't source alignment (intermediate object needed), it hasn't "undo" option for any action taken, it lacks animation and so on. The scene build with the software - unhandy. Either you build simple scene - one cam, one source, one background or you need to spend hours to build up something new.

Hope your 'copy' will help a lot. But I don't think that it could change the things. The application is too complex to be managed by casual user and too weak to become a pro tool. You'll just add one more menu entry and that makes application even harder to understand by a newbie.

Also, maybe this is off the topic, but "undo" for OBS (locked while recording/streaming) and one more "undo" for Studio Mode (resets after exit) is good step forward, I think.

But really, I don't know where Studio is moving, so let it exist. Maybe this is step forward too.

As for naming. The Studio uses Duplicate (scenes, collections, profiles) - maybe it is wise to use _Duplicate sources_ and change Device/File path/Whatever source has unique? Not only transform but the filters too? There is only a _Scene_ available for duplicating for now.

**Comment by RytoEX** [comment]
@SuslikV 
No need to insult Jim's work or OBS itself.  When I said:

> I'm not fully clear on exactly what purpose it would serve.

I just meant that I don't understand what added benefit it would create.  It was an invitation for you to explain your point of view on that feature request.  What would a user use the displayed "crop size/dimensions" info for?

My hesitance on it is mostly that I suspect users will see a read-only output of crop dimensions, become frustrated that it's read-only, and then ask that we make it so that they can directly specify crop dimensions.  Then, how do we determine which direction to crop?  Do we always crop the right and bottom edges?  Do we make it so that users can drag a source within its crop bounds?  Do we let a user specify which edges to crop?  It possibly introduces a bunch of future issues that I do not know how to handle.

I've already discussed this comment with a few other users, and I've heard some use cases for such displayed information.  As I said previously, I can probably whip up a patch for that feature, so I will look at working on that next.  However, **_as always_**, accepting patches is up to Jim.  There's no guarantee that he'll take that one, or even this one.

I did not want to provide a one-time copy-paste (such as Duplicate) because I wanted users to be able to copy the transform settings of one source and apply it to others _multiple_ times, as much as they want.  That is why there are two menu items (Copy and Paste) instead of one (Duplicate).

Duplicating sources is something else that I've looked into, again, at the suggestion of other users.

The purpose of this PR is that some people have complained that setting up multiple scenes to look similar in setup, but with different sources, is difficult because they have to hand transfer all of the transform and crop settings.  This PR makes it possible to avoid hand transferring those settings.  I appreciate your passion and the time you took to write your comments.  However, the purpose of this PR is not to address your other concerns about missing OBS Studio features.  If you have larger complaints about the state or direction of OBS Studio, this PR is not the appropriate place to discuss those concerns.  Write a feedback post in the forums, and tag Jim.

**Comment by SuslikV** [comment]
Because Studio always uses "Duplicate" as name for copy operations, then full copies (or ref) of sources probably could be named "Duplicate" too (if this feature planned in the future) no matter are you copy source or just extends another clone. So, you are free on "Copy transform" CTRL + C and "Paste transform" CTRL +V use. I think so. And the fear that "feature/keys" is used in other programs doesn't make any sense. Just make it and don't touch what Studio already has.

**Comment by RytoEX** [comment]
> So, you are free on "Copy transform" CTRL + C and "Paste transform" CTRL +V use. I think so. And the fear that "feature/keys" is used in other programs doesn't make any sense. Just make it and don't touch what Studio already has.

Again, this PR _does not_ add, change, remove, or modify any "Control+\<Key\>" global hotkeys.  I _only_ added and changed in-menu shortcut keys.  These are different things, as I discussed with @ThoNohT in previous comments.

**Pull request closed without merging**
