### PR TITLE
obs-filters: Optimize and fix alpha in color grade filter

### PR DESCRIPTION
**Pull request by c3r1c3**
Fix Alpha not being preserved in some cases.

### CODE REVIEW

**Comment by RytoEX** [comment]
To keep the commit message succinct, you could probably change the commit message to this:

> obs-filters: Fix Alpha not being preserved in some cases.

**Comment by c3r1c3** [comment]
Made the changes, but I don't see it on this page, even after force pushing.

**Comment by RytoEX** [comment]
Commit subject still gets cutoff by GitHub, which is actually more generous than other git clients, if I recall correctly.  =/  Best alternative I can suggest is this:

> obs-filters: Optimize and fix alpha in color grade filter

Or just leave it be and Jim will change it to whatever he wants later.

**Comment by c3r1c3** [comment]
I love it. Thanks. Hopefully Jim loves it as well. ;-)

**Comment by c3r1c3** [comment]
To reproduce the error that this code fixes:
Add source->Add Color Correction filter, and set opacity to 50%. Then add LUT Filter. Opacity goes away.

**Pull request closed without merging**
