### PR TITLE
UI: Implement panning in advanced audio controls

### PR DESCRIPTION
**Pull request by cg2121**
This adds panning to the advanced audio controls.

### CODE REVIEW

**Comment by SuslikV** [comment]
1) While 0.5f is skipping the panning, any value close to 0.5f will add -3dB to the almost centered signal (constant power panning law used). I mean, loudness lowers a bit as soon as you touch the ruler. I understand that it rare in use and will be skipped in most cases but what do you think about this? Maybe we need multiply of sqrt(2) when panning used? Of course, user can do it manually through the filters. The advantage of current implementation -  you can set center easily by your ears (max volume at the center position).

2) If _Audio_ set to mono in OBS Studio _Settings_ and panning not equal to 0.5f - application will crash in obs.dll (probably second channel not exist - you cannot assign data).

**Comment by cg2121** [comment]
I have fixed the crash when mono is set in OBS settings. I have disabled panning when this is set. I have also fixed the issue when panning is in the center.

**Comment by SuslikV** [comment]
No, no, no.  I didn't mean that the "1)" was wrong. Not this way. I was interested in your opinion only. It was better solution as for me. Because now all sounds will be at -3dB quieter and someone will complain about this.

**Comment by cg2121** [comment]
I've now added a switch case for different panning types.

**Comment by SuslikV** [comment]
Panning will be used with values about 0.6-0.7 mostly (my own estimation), this values close to 60 degrees or sqrt(3)/2. So, I can apply multiply of 2/sqrt(3) (+1.25dB) to each channel to make floor at 60 degrees. That means that at 45 (center) it will be only `20*log10(A) = 20*log10((2/sqrt(3))*sin(pi/4)) = 20*log10((2/sqrt(3))*sqrt(2)/2) = 20*log10(sqrt(2)/sqrt(3))` = -1.76dB lower; and at 90 (full right) = +1.25dB higher; just to keep same volume almost without overload at optimal channel balance.

I see this as:
```
if ((obs_source_get_panning_value(source) != 0.5f) && (!mono_output)) {
...
	there was my thoughts about 45 and 60 degree floor;
...
```
Also, there is an example when Advanced feature was removed:
https://obsproject.com/mantis/view.php?id=862
Something similar happened to OpenGL renderer under Windows.
This has very specific use too...

**Comment by c3r1c3** [comment]
Nice patch!

Currently there is no way to reset the pan bar to the middle.

If I'm understanding correctly what's happening, there is one L<->R bar and that controls both channels, so when any panning happens it 'combines' both channels of audio and moves them to the left or right( or the middle), which defeats stereo sources.

The only way I can see around it is to include 1 or 2 (or however many channels the device has) panning bars and pan for each channel. If the Mono checkbox is checked, I guess it would hide/deactivate all but the first bar.

Which leads us to the behavior of the "Downmix to Mono" option. It seems to combine both channels into a single channel and then outputs said mono channel twice, once on the left side and once on the right side, which seems to defeat the panning option. I think the solution would be to have OBS not double the audio.

**Comment by cg2121** [comment]
I been trying to figure out how to make so you can double click to reset the panning.

With stereo panning, if it is panned all the way to the left, the left channel will be the one heard and the right channel will be muted and vice versa.

**Comment by cg2121** [comment]
What I have implemented is more of a stereo balancer. The further left the slider is the quieter the right channel is, and vice versa.

**Comment by cg2121** [comment]
Here's where I got the equations from:
http://www.hackaudio.com/digital-signal-processing/stereo-audio/linear-panning/

**Comment by c3r1c3** [comment]
Thanks for sharing.

In your repo's branch I'm submitting some additional code. I'll continue there.

**Comment by SuslikV** [comment]
@c3r1c3 perfect catch. "Downmix to Mono" important. The panning should apply last. But I see as more posts appear in the thread the worsen it (feature) becomes...

"Downmix to Mono" is just averaging channels feature. This is just bad wording (downmix to mono). It should average any signal between all channels (making planar sound). For example, input is 2 channels stereo, the Left channel 0% of amplitude, Right channel 100%, then `"downmix to mono" = L = R = L*1/2 + R*1/2`. Result: L= 50%, R= 50% of the same data (still 2 channels audio).

OBS Studio supports only stereo output.

**Comment by pkviet** [comment]
nice PR. 
Could you change your check of stereo condition from :
`if (strcmp(speakers, "Mono") == 0)
 		panning->setEnabled(false);
 else
 		panning->setEnabled(true);`

to:

`if (strcmp(speakers, "Stereo") == 0)
 		panning->setEnabled(true);
 else
 		panning->setEnabled(false);`

This will have the same effect but it creates compatibility if other speaker layouts are enabled in the future (as in my PR)

**Comment by pkviet** [comment]
it is a good idea to pan per channel; so +1 also about c3r1c3 remarks

**Comment by jp9000** [comment]
I want someone here to give me a specific case where panning is useful to have in obs itself.

**Comment by SuslikV** [comment]
@jp9000 under the "edit" section: [Only mono audio, can not achieve stereo](https://obsproject.com/forum/threads/only-mono-audio-can-not-achieve-stereo.52523/#post-231839)
but this is only my own thoughts. Because OBS Studio captures devices only and for each device I can access balance settings from the Windows mixer. So, the feature not needed and should be removed. 

Only if you planning to use "Downmix to Mono" then Panning L to R required inside obs (of course, if it applies last). And because it is hard to say if somebody needs this feature (downmix + panning) then it will be better to remove it completely.

Also, panning of the multi-channel is not just LtoR.

**Comment by jp9000** [comment]
Going to close this because it's incompatible with the surround sound code.  However, keep this branch around -- there should be a way to adapt it.  If it ends up being too much trouble, we can probably just make an audio filter and limit its capability to stereo/mono inputs only.

**Comment by Wiethoofd** [comment]
> I want someone here to give me a specific case where panning is useful to have in obs itself.

If you use OBS together with [NDI](https://github.com/Palakis/obs-ndi) to capture multiple devices on a single production PC this would allow you to create a *splitscreen* scenario where you position audio from your inputs to be on a specific side to match where they are on the screen.

Similar when you have separate audio inputs available (for instance 2 miced up people or audio only NDI sources), you would have the ability to space them out, so it doesn't sound like they are occupying the same chair & microphone but are in fact further apart.

--- 
At the moment having the panning slider in the Advanced Audio Properties without proper indication that they are in fact unable to be moved defeats the purpose of having them at all.

**Comment by pkviet** [comment]
@Wiethoofd  or one could write a filter implementing channel routing or mixing using libswresample; i might write one when i have some free time. It should not be very difficult.

**Pull request closed without merging**
