### PR TITLE
obs-filters: Fix heavy distortion in Noise Suppression filter

### PR DESCRIPTION
**Pull request by jdpurcell**
Fix for the issue described here: https://obsproject.com/mantis/view.php?id=1083

~~Unfortunately I don't have the ability to build/test this right now, but I hope it's better than nothing. If not, feel free to close the PR.~~
**EDIT:** I've now built and tested this, it does indeed solve the issue.

### CODE REVIEW

**Comment by SuslikV** [comment]
Yeah, it solves the mentioned issue.

The @RytoEX should say that https://github.com/jp9000/obs-studio/pull/1113/files#diff-5ab27ab1468a600053d50b1305fffd97R164 string is too long (72 is max).

**Comment by RytoEX** [comment]
@SuslikV The line limit is a strongly preferred 80 columns, but that line is still longer than even that.  I just haven't gotten around to reviewing this yet.

**Comment by SuslikV** [comment]
The only reason why I put some attention to this commit because of simple solution. Usually, simple and temporary workarounds merged first. Internal clipping is not the best option for the filter itself but it was in the original code, so. I think, it is acceptable right now.

**Comment by jdpurcell** [comment]
Yeah it's a shame it can't stay floating point all the way through, but unless someone is brave enough to rework the Speex preprocessing code, I'm not sure what else to do 😄. You could change the float <-> int scale factor to (INT16_MAX / 2) to give some more headroom, but then you're losing a bit of precision of course.

IMHO simply clipping is a major improvement over the current behavior. The distortion caused by the overflow is quite awful / alarming, so leaving it as-is would be really unfortunate. As an example, here's what it sounds like when the overflow is triggered (**volume warning**): https://clips.twitch.tv/CovertDeliciousToothNomNom

**Comment by jp9000** [comment]
Super minor nitpick - just changed the second if to an else if.  Merging shortly.  You'll see "closed from [commit]".

**Pull request closed without merging**
