### PR TITLE
libobs: Log which security software is in use

### PR DESCRIPTION
**Pull request by notr1ch**
This is a Windows specific PR that uses the Windows Security Center API to log which security products are installed and active on the user's system. This aids in debugging issues caused by various 3rd party anti-virus products that often interfere with the correct operation of OBS.

**Needs testing** - I won't be able to access my Windows 10 development box for a while as I'm traveling, and this code doesn't run on Windows 7 as the API is unavailable.

### CODE REVIEW

**Comment by SuslikV** [comment]
I don't think that this is good idea. Maybe standalone trouble-shoot utility that will show all required info about incompatible soft & hard would be acceptable here.

When Studio uses external libs, system settings or hw - then, I understand, it can be added to the log. But loggin soft that is standalone product... There are progs that doing graphics mods, overlays, overclocks etc and can break OBS Studio experience too. Not only security software important, I mean.

**Comment by notr1ch** [comment]
While it's true lots of software can cause issues, antivirus has been one of the main sources of persistent user problems (eg Bitdefender's Webcam Protection or Avast's Game Mode). Logging which antivirus is present will make diagnosing these kinds of problems much easier.

Antivirus products have a much larger install base than hooking tools like RivaTuner / FRAPS / etc so this will potentially help in a lot more cases.

**Comment by SuslikV** [comment]
It is sad, that we need build-in diagnosing tool because of (and only for) third party software. Don't take in mind, it's just a comment from me.

**Comment by jp9000** [comment]
Fixing up the styling, then merging.

**Pull request closed without merging**
