### PR TITLE
Dark theme and theme selection.

### PR DESCRIPTION
**Pull request by Socapex**
This PR adds a dark theme. It also adds the possibility to select themes from settings window.

- Themes folder is scanned for themes.
- Themes placed in data/obs-studio/themes/*.qss
- Selecting a theme previews it.
- Dark theme is still in "beta", but hopefully you guys can help make it even nicer!

First, I really hope everything is on guidelines. I believe it is. Also, I am still a student and as such I may have made outrageous mistakes. There may also be more elegant ways to do some of the things I do, please be patient and simply share that with me.

Also, I'm really sorry for the big commit. The issue is, adding stuff separately would break build, and I don't know where you stand on that (if each commit has to build on its' own).

Enjoy sexy dark theme xD

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
ok to test

**Comment by hwdro** [comment]
Don't add images that belongs to a theme into obs qrc.

**Comment by ubuntuaddicted** [comment]
Awesome! Thank you for creating a dark theme, it'll fit on my desktops much cleaner now.

**Comment by Socapex** [comment]
Ready for merge unless issues arise. If you have bugs/minor complaints, please include a screenshot. I have no way to test it on Virtual Machines unfortunately.

**Comment by jp9000** [comment]
ok to test

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
Merged here: https://github.com/jp9000/obs-studio/commit/9b44b368b73330cc27b61d32781c5e310a62e729

Mostly just cleaned up the commits.  Please check them out if you have time to see what I was talking about earlier.

Oh I did do one minor thing, I removed the settings window icon changing code because I felt a bit uncomfortable with it, and just changed the "advanced" icon to have a white outline so that it's visible in both light and dark themes equally.

**Comment by ubuntuaddicted** [comment]
Awesome, thanks guys!

**Pull request closed without merging**
