### PR TITLE
Icon is redrawn for better visibility and contrast

### PR DESCRIPTION
**Pull request by TotalCaesar659**
The icon is redrawn for better visibility and contrast, and also for unification with commit https://github.com/jp9000/obs-studio/pull/696

### CODE REVIEW

**Comment by DDRBoxman** [comment]
This ico file only contains a single 64x64 image asset. While I can't speak for asset redesigns, I can say that we can't merge this until the other resolutions are packaged, including up to 256x26 and down to 16x16

**Comment by TotalCaesar659** [comment]
Oh, sorry. Could you give me advice about how to add these resolutions? And list of the resolutions.
I made this ICO by Gimp on Linux, but I don't know how to add more resolutions to the ICO with it.

**Comment by DDRBoxman** [comment]
I usually use IcoFx but imagemagick should be able to do it. http://www.imagemagick.org/discourse-server/viewtopic.php?t=14080

**Comment by TotalCaesar659** [comment]
Re-created the icon by Imagemagick, please check this PR https://github.com/jp9000/obs-studio/pull/745
I close this one.

**Pull request closed without merging**
