### PR TITLE
obs-text: Text Source fixes and feature additions

### PR DESCRIPTION
**Pull request by Xaymar**
Fixes/Adds the following:
- Fix color bleeding with outline and background enabled.
- Fix outline causing Text fill to behave weird with overlapping glyphs.
- Add option to choose Text render mode (add to background or replace background).
- Add option to choose Outline render mode (over text, under text, replace text or replaced by text).
- Splits Text and Background rendering to allow the above to work cleanly.
- Add option to disable Anti-Aliasing if needed (for 8-Bit Fonts and similar).
- Anti-Aliasing for Text is now AntiAliasGridFit if enabled otherwise it's SingleBitPerPixelGridFit (fastest).
- Anti-Aliasing for Outline is now SmoothingModeAntiAlias8x8 if enabled otherwise SmoothingModeNone.

### CODE REVIEW

**Comment by Xaymar** [comment]
Part 1 of this PR is splitting the rendering of the outline from the Text. Right now, it renders the text infront of the outline, but it might be necessary to reverse that order.

Part 2 fixes a bug in GDI+ Path rendering with texts that would cause the Path to not be Anti-aliased because Paths require hinting to be aliasing or a half-pixel offset. In this case, I added both and increased the anti-alias matrix to 8x8 (technically 8xSSAA). Fixes color bleeding at low texture sizes and looks better with larger text sizes and background enabled.

**Comment by Xaymar** [comment]
The choice left to make here is weether to add a dropdown on how to do compositing (over or copy) and how text should interact with the outline (text under outline, text over outline, text replaces outline).

**Comment by Xaymar** [comment]
Example Pictures:
- [Render Mode Additive, Outline Mode 'Text Over Outline'](http://cdn.xaymar.com/private/2016/09/obs64_2016-09-30_01-19-55.png)
- [Render Mode Additive, Outline Mode 'Outline Over Text'](http://cdn.xaymar.com/private/2016/09/obs64_2016-09-30_01-20-15.png)
- [Render Mode Additive, Outline Mode 'Text Replaces Outline'](http://cdn.xaymar.com/private/2016/09/obs64_2016-09-30_01-21-29.png)
- [Render Mode Additive, Outline Mode 'Outline Replaces Text'](http://cdn.xaymar.com/private/2016/09/obs64_2016-09-30_01-21-38.png)
- [Render Mode Replace, Outline Mode 'Text Over Outline'](http://cdn.xaymar.com/private/2016/09/obs64_2016-09-30_01-21-54.png)
- [Render Mode Replace, Outline Mode 'Outline Over Text'](http://cdn.xaymar.com/private/2016/09/obs64_2016-09-30_01-22-05.png)
- [Render Mode Replace, Outline Mode 'Text Replaces Outline'](http://cdn.xaymar.com/private/2016/09/obs64_2016-09-30_01-22-14.png)
- [Render Mode Replace, Outline Mode 'Outline Replaces Text'](http://cdn.xaymar.com/private/2016/09/obs64_2016-09-30_01-22-22.png)
- [All in One](http://cdn.xaymar.com/private/2016/09/obs64_2016-09-30_02-17-55.png)

Default Render Mode is Additive and default Outline MOde is 'Text Over Outline'. These settings will most likely only be used by few, but allow quite a lot of customization for those using the background feature.

Edit: The UI looks like this: [1](http://cdn.xaymar.com/private/2016/09/obs64_2016-09-30_01-23-19.png), [2](http://cdn.xaymar.com/private/2016/09/obs64_2016-09-30_01-23-33.png)

**Comment by RytoEX** [comment]
I imagine @jp9000 will want the commit message formatted as 50/72.

**Comment by Xaymar** [comment]
Render Mode and Outline Mode are now hidden behind a checkbox called "Show Advanced Options", so that new users are not confused by this.

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by kingargyle** [comment]
@jp9000 any chance of reviewing this and possibly getting it into the build.  Would help clean up some edge cases for the text in certain videos.

**Comment by Xaymar** [comment]
It would be ideal if we had a better text renderer than the one currently in use, these changes only hide the real problem.

**Pull request closed without merging**
