### PR TITLE
UI: Add ability to output to window

### PR DESCRIPTION
**Pull request by cg2121**
This adds the ability to output to a window (similar to the projector outputs).

### CODE REVIEW

**Comment by WizardCM** [comment]
For consistency, and to avoid confusion, I feel `Open in Window` should read `Windowed Projector` as that'd align with `Fullscreen Projector`, because people already know what those are.

Love this idea though, and have seen it requested a fair bit recently.

**Comment by cg2121** [comment]
I have now changed the wording.

**Comment by kingargyle** [comment]
Would love to see this added, it might fix some issues I'm seeing on Linux with the current projector.

**Comment by egordorichev** [comment]
Yes, those bugs with linux display are so annoying!

**Comment by jp9000** [comment]
Fixed it so that it centers the window, and fixed a crash on exit that could happen due to the windows not being freed soon enough.

**Pull request closed without merging**
