### PR TITLE
rtmp-services: Added WatchPeopleCode.com to services list

### PR DESCRIPTION
**Pull request by gkbrk**
Added the WatchPeopleCode streaming server to the rtmp services list.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by raoulvdberge** [comment]
:+1:

**Comment by jp9000** [comment]
Going to implement some changes before this is merged

**Comment by gkbrk** [comment]
Any updates/changes that I need to make?

**Comment by jp9000** [comment]
Negative, still working on the new services plugin (right now as we speak)

**Comment by jp9000** [comment]
https://github.com/jp9000/obs-studio/commit/b373f82c9eecdf382f8601f0a92a4330c835972f

**Pull request closed without merging**
