### PR TITLE
Update services config for Restream.io

### PR DESCRIPTION
**Pull request by Dead133**
Update Restream.io ingests list and set recommended keyframe interval to 2

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by notr1ch** [comment]
You need to increment the version number in the package file too.

https://github.com/Dead133/obs-studio/blob/8ef76e62a3d0e51b5a11f544553a409117256467/plugins/rtmp-services/data/package.json

**Comment by Gol-D-Ace** [comment]
Also forcing 2 seconds might not be the best idea. You can use different
services with restream and beam.pro for example wants 1 second. I recommend
not setting a recommended keyframe interval.

**Comment by Dead133** [comment]
Thanks, @notr1ch
I did amend to my commit with version update.

**Comment by Dead133** [comment]
@Gol-D-Ace 2 seconds keyframe interval is the recommended setting for Restream.io itself, as well as for most of the services.

**Comment by jumoog** [comment]
@Gol-D-Ace 2 it's needed for HLS Service

**Pull request closed without merging**
