### PR TITLE
obs-transitions: Add audio monitoring option to stinger transition

### PR DESCRIPTION
**Pull request by OsirisNL**

### CODE REVIEW

**Comment by SuslikV** [comment]
I like the idea to Monitor stinger transition video file.

Any way to have an checkbox to be able to add it (audio from Stinger transition) to the Mixer's pane as source, and use Advanced Audio Properties for Monitoring setup? (Of course, short sounds and movies are hard to edit because they disappear from Advanced Audio Properties on playback end. And while Media source possible to loop, preview stinger transition loop and thus volume adjustment not available right now)

**Comment by OsirisNL** [comment]
A stinger is usually not very long, so I don't see the point of adding the hidden Media Source to the mixer or advanced audio properties. What might be possible is a volume slider in the stinger's properties.

**Comment by jp9000** [comment]
Made some indentation modifications.  Kind of wish there was a way to use the main audio monitoring options in the UI, but due to the nature of the design it's sort of convoluted.  I suppose this will have to do for the time being I suppose.  Merging.

**Comment by jp9000** [comment]
Merged via dab278e1b6

**Pull request closed without merging**
