### PR TITLE
UI: Add recording and streaming indicator

### PR DESCRIPTION
**Pull request by cg2121**
This changes the color of the buttons when streaming and recording to red when they are active.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
Actually after some discussion (which I should have requested more of) I'm removing the merge -- I agree that we need an indicator, though I feel that this was more of a stop-gap solution rather than something I'd consider a "solid" solution.

Your solution was simple, and when merging I thought "this is a decent solution, and we can improve it later", but that was a poor decision on my part, and something I need to stop doing.  I should have requested more feedback.  After merging, other people pointed out that it was not the right solution because it just overrides the QSS which wasn't ideal, especially with the fact that we support two sets of stylesheets.

I should have asked about that on the original PR.  I apologize for that.

I'm really terribly sorry for the trouble -- if you happen to have time, could you try making a set of icons instead, and using them with the buttons?  Though I'm not sure of what sort of icons to use.  I'd like to see what it looks like though at least.  Perhaps a simple color-filled circle would work.  I'm open to ideas.

**Comment by aFoxNamedMorris** [comment]
@jp9000 Why not something like a red circle for record, and a broadcast tower with an aura for streaming? If not recording or streaming, the corresponding icon could be grayed out, when active, the color would become present.

**Comment by Jack0r** [comment]
obs-studio_stream_rec_notification

**Comment by aFoxNamedMorris** [comment]
@Jack0r That's great! Gets the point across without being too busy.

**Comment by dodgepong** [comment]
Whatever the solution is, if it's based on color, make sure it's friendly to those who are colorblind.

**Comment by robske110** [comment]
Good thought there :)

**Comment by cg2121** [comment]
I actually like the icon idea better myself. It is a lot more subtle than my original idea and not so much in your face.

**Comment by Djidiouf** [comment]
The solution proposed by @Jack0r is perfect. I really miss that functionality in my use of OBS. @jp9000 , what do you think about that solution?

**Pull request merged**
