### PR TITLE
Ffmpeg source plugin

### PR DESCRIPTION
**Pull request by kc5nra**
Adds a simple ffmpeg input source to obs-studio.

### CODE REVIEW

**Comment by jp9000** [comment]
add to whitelist

**Comment by Dr-Shadow** [comment]
Thank you for this feature, this is exactly what I was needing !
I succesfully tested it with a public rtmp flux.

**Comment by ubuntuaddicted** [comment]
Does this mean that I can add any source that I put through ffmpeg? Because I believe I can pipe the output of an HD-PVR through ffmpeg. The problem was that the kernel module hdpvr doesn't really decide the hdpvr stream, it just allows the playback of it so it's still an encoded TS bitstream. I posted about it not working with the V4L2 plugin on the linux forums

**Comment by kc5nra** [comment]
The plugin feasibly allows everything that ffmpeg can play.  So if you normally used ffmpeg -i /dev/some/device, you could put the same /dev/some/device in the input field and it should pull frames from the device correctly.  I don't have any test devices so I can't actually verify this.

**Pull request merged**
