### PR TITLE
Master

### PR DESCRIPTION
**Pull request by cleoag**
texture3d support added

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by RytoEX** [comment]
Could you be a bit more descriptive about what this does?  If @jp9000 would like, I can go through a code review with you to cleanup the commit and PR.

**Comment by jp9000** [comment]
I don't think I'll merge volume texture support unless you have it for both D3D11 and OpenGL.

Why do you need volume texture support just out of curiosity?  If you're just implementing it just for the sake of implementing it, it's not really worth it.

If you do need volume texture support, please implement the opengl version as well, then feel free to re-open a pull request.

**Comment by cleoag** [comment]
i need them for 3d LUT filter (https://en.wikipedia.org/wiki/3D_lookup_table), already did it

will do opengl version on next week probably

**Comment by jp9000** [comment]
Additionally, when you make a pull request, it should be rebased off of upstream master.  Don't have unnecessary merge commits.  The commit message title/body also need to follow our guidelines.  50/72 for title/body, in present tense, plus prefixing the commit title with the module being modified.  So for example, "libobs-d3d11: Add volume texture support" would be what you'd probably use, with the body explaining your need.  If you want to see how commit messages usually look just look at our commit history.  See http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html for more information on good commit message standards.

We also have code styling guidelines, see https://github.com/jp9000/obs-studio/blob/master/CONTRIBUTING for more information.

**Pull request closed without merging**
