### PR TITLE
Don't nudge sources if preview is locked

### PR DESCRIPTION
**Pull request by CoDEmanX**
Fixes https://obsproject.com/mantis/view.php?id=588

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by robske110** [comment]
And nice PR!


(The bot failed.)

**Comment by Simran-B** [comment]
The issue on mantis can be closed: https://obsproject.com/mantis/view.php?id=588

**Pull request merged**
