### PR TITLE
UI: Add import/export of scene collections & profiles

### PR DESCRIPTION
**Pull request by cg2121**
This adds importing and exporting to the menus of scene collections and profiles.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by RytoEX** [comment]
Dang.  This one was in my list of items to do later.  Nice work!  I did a quick glance over the PR for code style, and I didn't see anything that jumped out at me.

Seems you have some conflicts to resolve though.

**Comment by Fenrirthviti** [comment]
This looks great, but might want to check for and add a warning for anyone trying to import Classic scenes/profiles. Ideally, it should allow import/parsing of the Classic scenes and profiles, but this would take much more work. Possible that the work Rodney did here: http://obsproject.com/forum/resources/obs-classic-to-obs-studio-scene-converter.430/ could be leveraged?

**Comment by RytoEX** [comment]
@Fenrirthviti 
I think @derrod's converter still needs some work before it's considered for inclusion in core OBS Studio.  Though, I'm not sure exactly which (edge) cases it doesn't handle.  For this PR, I think simply detecting and disallowing imports from OBS Classic would be fine.

**Comment by SuslikV** [comment]
May I bite you too?

1) Scene Collections/Profiles hasn't version info, as I see. How you plan to detect further improvements in code and compatibility detection if you do not add this info to the Profile and Collection files itself? Users always do wrong, just imagine if I want to import "OBS Studio 2" files to the "OBS Studio" not just "OBS Classic" (and Studio still hasn't "safe" run option with new profile and collection).
2) Do you allow to the user to rename Imported collection and profile (or update/overwrite it) if the same profile/collection already exist?
3) Exported Profiles stored as folders or single files (.zip maybe)?
4) Users will exchange the collections and profiles - is it possible to include Sources origin in the exported files (not only path to the media) as an option maybe? There is a lot of work to do. Maybe _create Sources folder..._ option when you import Collection with Sources origin etc.

**Comment by SuslikV** [comment]
In general, you didn't leave place to improve the commit or feature itself. Dead end.

**Comment by cg2121** [comment]
The users can't import Classic's scene collection because the import file dialog only allows .json files, Classic's were .xconfig files. As for profiles, users can only select folders, Classic had only one file when exporting profiles. The code already detects if the files are valid or not, I guess I could display a warning when this happens.

The export profiles does export to a folder.

**Comment by SuslikV** [comment]
That's why we had the Architect in the matrix movie - he had vision of whole project not just how to join the parts...

Still think that using intermediate files to store the profiles (.obspr for example) and collections (.obssc for example) is better. If not a header and own format, then just a .zip compressed file with a comment inside or so. And maybe later, you would like to include something into the exported file (other data, comments, include/exclude streaming key etc.) as Studio improves and updates in time.

Don't take in mind - it's just about the feature itself, not about the commit.

**Comment by jp9000** [comment]
It's useful to share profiles, though scene collections not so much due to it storing local assets, and I don't want to make some elaborate scene collection exporter where it includes all files.  I don't mind merging this as-is for now, though how useful it is is debatable.

I might end up removing the service file from profile exporting and just make it export the ini files though, I don't really want service info (such as stream key/etc) to be shared.

**Comment by Gol-D-Ace** [comment]
This is also useful for local backups. Not everyone wants to deal with the folder structure behind the scene.

For local backup scene collections and profiles are quite useful.

Maybe warn the user that profiles contain stream keys but do not throw them just away.

**Comment by Heufneutje** [comment]
Or provide an option they have to check if they want to include the keys.

**Comment by RytoEX** [comment]
@Gol-D-Ace Beat me to it.  If the exports/imports are used by users for their own backups or setup duplication, then _not_ having the stream key would probably be confusing ("Why isn't it just working?  I imported my backup!").  That said, I do understand the concern about users sharing their exports with _other_ users, but I think that warning them should suffice for most cases.

@Heufneutje's suggestion would also work.

**Comment by Heufneutje** [comment]
The main problem with showing a warning and keeping the keys is that if the user **does** want to share the profile with somebody else, they would still need to go through and delete the keys manually

**Pull request closed without merging**
