### PR TITLE
net-if: Stop trying when buffer exceeded

### PR DESCRIPTION
**Pull request by bl4**

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
Changing the title, then merging

**Comment by jp9000** [comment]
Wait a sec -- no, your new code is incorrect.  It's supposed to keep looping if ret == ERROR_BUFFER_OVERFLOW.  Your older code functions correctly.

**Comment by bl4** [comment]
*facepalm*

Thanks

**Pull request closed without merging**
