### PR TITLE
UI: Add raw text and text file to drag&drop support

### PR DESCRIPTION
**Pull request by Xaymar**
This adds raw text (drag and drop from anywhere as text) and text file (.txt, .log) support to obs studio.

### CODE REVIEW

**Comment by Xaymar** [comment]
Example:
- Raw Text
- Text File

Video: https://www.youtube.com/watch?v=OaNroAY3Nn4

**Comment by robske110** [comment]
👍
Don't know who will actually use this though.

**Comment by Jarod997** [comment]
If people stream using Studio view, it's handy to add instant messages on the fly. I was looking to do this just yesterday - I would have had to create a text item, set the size, properties, position, etc then fade/cut it into the live side. But I didn't because I was more busy with the streaming. Good job!

**Comment by gamegenten** [comment]
It looks super useful to me. :)

**Pull request closed without merging**
