### PR TITLE
Convert OBSBasic service to a vector

### PR DESCRIPTION
**Pull request by 2mac**
I'm working on enabling users to stream to multiple servers at once. This is the first step in making that possible.

Please review my changes, and let me know if anything needs tweaking so far. Otherwise, I'd like it to go into testing to make sure the backend works before I spend time working on a UI for this.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
My review will be pending.  I have to work on getting 0.12.0 out first.

Typically, before you start making significant changes, it's always recommended that you discuss your vision on how you'd want it to work with the rest of us before making significant code (which you seem to be doing somewhat, thankfully).  Multiple streams is perfectly doable, but our concern again is its user interface; ease of use, whether it would confuse users, would it add more steps to setting up a single stream, etc.

Just as a note, unrelated to the code:  your commits could never be merged as they are now, just in case that's what you were intending.  There are multiple issues with the commits alone.  See the 'contributing' file, and observe our commit history to see how our commits and commit message are constructed.  We need good commit messages and commit titles that abide by the common 50/72 guidelines.  Two commits that do the same thing should be squashed.  Any commit that does more than one thing should be split for each thing it does.  Each commit should typically be fully compilable and safe to run when one sets the head to that commit.  No unnecessary merge commits

Also preferably no needless change to whitespace:  e.g. https://github.com/2mac/obs-studio/commit/ef1dfefa41dc1321925aec9b7de819dfd716965f#diff-d2ae3dbbc1ca4c1dcc778937ecfb4d79R370 - this would be classified both as "doing two things in one commit", and "changing code unnecessarily".

I'm guessing in general that this is one of your first times submitting changes to an open source project and using git for a major project.  Unnecessary merge commits especially are a sign of inexperience with git.  Again, these things are all okay as long as they're fixed before a merge (and again, whether we even accept this code has yet to be decided).  We've all been there, everyone has to have a first time; I made similar mistakes a long time back, probably even worse mistakes.

Pull requests can be rebased/force pushed before being merged, which will update the pull request, so they can always be edited and fixed (not that I'm asking you to do that now necessarily, that should typically happen before you intend to have it merged).

**Comment by jp9000** [comment]
That being said, as for your proposal, I'm not sure how I like the idea of this particular user interface (we will have a multiple later) having a programmable number of simultaneous streams.  I was originally designing this particular interface to be hard coded at a max of probably two streams at most, not a variable number, mostly as a means of making it more simple to configure.  As much as people might dislike hearing me say this (and I only say this for this particular user interface), a variable numbers leads to painful configuration for users because they have to juggle needlessly adding/removing/renaming/etc.  I generally dislike forcing 99.9% of the users who won't use this feature to have to deal with a feature that only 0.1% of the other users will want to use.

I was going to let the whole "as many as you want of anything" sort of thing be put in to the more advanced UI (which hasn't been created yet), rather than the basic UI.  It's understandable you wouldn't have known about that though I suppose.

**Comment by 2mac** [comment]
Regarding the contribution process, I will review the file. How would you recommend revising the commits now that they have already been made?

As far as the variable list, I always use them to future-proof the code. Even in a case where I only planned to start with one stream, I would have made a variable list to support it in the future since the backend is already abstracted in a way which allows this.

For the UI, it's a bit imperative that it be possible to add an arbitrary number of streams. I intended on doing this with an anonymous list: the streams are not named, just numbered. The reason for this is that I have a client who has commissioned me to make these changes after talking with one of the main developers (he did not say who), because he was told that it was technically possible but lower on your priority list. It is higher on his priority list, and he knew me to be a supporter of libre software. That's not to say that there can't be a "basic" interface which hides the ability to have multiple streams from the user, but my client needs to be able to add as many as he wants, or else this work is pointless, and I can't fulfill his request. This is why I used a vector instead of a static array.

As stated, I'll review the contributing document. I already knew some of the commits weren't done perfectly, and I only did them to get things up to my server so I could work from another machine without using rsync or similar to just copy files. I don't remember about the first merge commit, but the second one for sure was needed to resolve conflicts.

**Comment by jp9000** [comment]
Well like I said it's perfectly fine if things aren't perfect, they can always be fixed, and you'll gain experience in doing so.  If you've never fixed up git commits before and need help, feel free to get in touch with me and I'll take some time to show you how to fix things up if you need, though it should probably wait until after a firm decision about the design.

Again though, this user interface wasn't really meant to use a variable numbers of streams.  It makes configuration more complex than it needs to be for the vast majority of people.  This particular user interface is designed for ease-of-use, not really so much the advanced functionality.  The key importance with this UI is that the casual users should not have to deal with any of the advanced features if they don't want/need to.  Though providing advanced functionality is fine, but it just needs to be separated from basic functionality.

For example if your proposed change to add multiple streams impacted casual/new users in any way, I wouldn't really want to do that.  For example, look at the way I separated "simple" and "advanced" outputs.  By default simple output mode is used, and basically makes it so a user only ever has to enter in their bitrate, and then almost everything else is automatically set up.  Makes encoder config super simple and quick (though even now it still needs to be more simple than it is, which is why I want to write a setup wizard in addition).

I wouldn't want to ever make it more complicated than that for new/casual users, that's all I'm really saying.

I kind of wish I had the advanced UI up and running so you had more options for this sort of stuff. that way you could do all the nifty things you want to do and make as many complex features as you want.

So many plans, so little time and so few skilled enough to handle it.

**Comment by 2mac** [comment]
Let's first focus on getting this change ready for merge. Once this is done, we can start talking about UI issues.

I know that you don't have time to be rushed over this, but I do have pressure from my client, and I need to at least have direction in a timely manner. My ideal would be to agree on a design so that it can be added (either to an advanced interface or not) without requiring me to maintain my own concurrent version of OBS which supports the interface. This user requires this feature for his business, and lack thereof is forcing him to run nonfree software at the moment, so it is high on my priority list.

First thing's first. Let's find a time to talk about fixing up the commits in a way that follows contribution standards so that this backend change can be merged. After that, we can find another time to talk UI.

**Comment by dodgepong** [comment]
With all due respect, Jim's obligation is to the software and the code base, not your client. Can you not just implement what you need for your client and make a custom build for them? I don't see why there is time pressure for this to be merged.

**Comment by 2mac** [comment]
Jim and I discussed some things last night over IRC. We had actually talked in the past in the development channel about adding this feature, so I suppose we'll continue with that and find the best way to make a UI to be added.

Yes, I'm fully capable of making my own custom build, but maintaining my own version is out of scope.

**Comment by 2mac** [comment]
I've redone the commits and combined them into one.

**Comment by Kazunekit** [comment]
Just an outsider's idea: let a plugin handle streaming if the plugin hooks into the streaming. This way you can have multiple or single streaming dependant on what the user wants instead of forcing something on everyone.

 I haven't looked in the code, so sorry if it's not possible. In such case please disregard this message.

**Comment by jp9000** [comment]
Haven't forgotten about this, the merge has conflicts so something will have to be resolved.  I'm trying to make some time for it but still getting pretty swamped by higher priority items.

**Comment by jp9000** [comment]
I'll probably end up resolving the conflicts myself at some point, and fine-tuning the code a bit more to my liking.  I'm still trying to get a develop plan of attack for the whole multi-streaming thing that I'll feel comfortable with.

**Comment by jp9000** [comment]
We're going to put this off until we've decided on a way to handle multiple streams elegantly.  Unfortunately multiple streams is not a high priority at the moment either so this pull request would probably just sit around forever.  I can't help with your situation however, that's not our responsibility.

**Pull request closed without merging**
