### PR TITLE
rtmp-services: Update Facebook Live recommendations

### PR DESCRIPTION
**Pull request by Jack0r**

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by WizardCM** [comment]
That is not the recommended video bitrate but the "recommended maximum," but yes, the audio should be 128 kbps. https://www.facebook.com/facebookmedia/get-started/live

**Comment by dodgepong** [comment]
That is what this PR changes. 4000 is being set as the "max video bitrate".

**Comment by WizardCM** [comment]
Yeah, I realised that directly after posting. Provided a source for reference. :)

**Comment by RytoEX** [comment]
Doesn't plugins/rtmp-services/data/package.json also need a version bump with this?

**Comment by Gol-D-Ace** [comment]
It does @RytoEX

**Comment by Jack0r** [comment]
I knew I forgot something. Package file is also updated now.

**Comment by Gol-D-Ace** [comment]
Could you squash the commits?

**Pull request merged**
