### PR TITLE
UI - save size/position and drag drop to reorder.

### PR DESCRIPTION
**Pull request by Socapex**

### CODE REVIEW

**Comment by Socapex** [comment]
This pull request will get Sources drag&drop to reorder, so do not merge yet. Though code standard and critics are welcomed. I will place stubs for Scenes drag&drop reorder, but until a similar function to
obs_sceneitem_set_order is implemented, it will wait.

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by Socapex** [comment]
Its not ready yet. Can someone on windows confirm that d01456f doesn't save positions outside of screen?

**Comment by Jack0r** [comment]
It saves window position and size on windows, but what do you mean with outside of screen?

**Comment by ubuntuaddicted** [comment]
I'm betting he means it saves it's position outside of the current screen it's on. If there 2 displays and its on display 1, displays 1 screen size is 1920x1080 for example. Maybe....

**Comment by Socapex** [comment]
No, well yes in a way. Lets say you drag the window so its half-way out of screen. Does it reload there, or is the window 100% visible?

**Comment by Jack0r** [comment]
It will keep half the window of screen.

**Comment by reboot** [comment]
If the position and size is saved correctly all the application can do on restart is request a certain position and size. It is still the decision of the operating system/window manager if the window is placed at the requested position or if it is placed differently, for example to not be outside of the visible screen. So you can never guarantee that it will keep the same position and size. Usually that is a good thing to do, because if an application saved a position that is completely off screen, maybe due to a resolution change, it would be bad.

**Comment by Socapex** [comment]
So... it's ready then? :)

Ty for the info Reboot, first time doing such a feature. I wasn't sure everything was ok.

**Comment by jp9000** [comment]
Hey when you get time take a look at this:  https://github.com/jp9000/obs-studio/compare/scene-item-reordering

- Fixed the commit messages:
  1. Messages need to start with the module name
  2. Message titles shouldn't end with a period
- Made it so that the UI still operates on the reordering signal so that it'll still respond to the signal (just resorts the list box)
- Fixed a potential unsafe dereference in this commit: https://github.com/Socapex/obs-studio/commit/ac44c871afb712eb50b06cfa753870518fcb4420 -- the first_item variable isn't guaranteed to have a previous item
- Removed https://github.com/Socapex/obs-studio/commit/32b3ddb0ef9d921681ba0c0614e966b0110e26c3 - I think you left it from your previous revision by accident
- Fixed a bug here: https://github.com/Socapex/obs-studio/commit/27c56334f928f3424d8b8ce26411dffdba9e561f#diff-57fee00864acfedbf5dfd179cdcd5eb3R722 (you forgot to set it to the new name you gave it, "reorder")
- Squashed https://github.com/Socapex/obs-studio/commit/15d7316c1cb39b174735123ef6125139ad9a9462 and https://github.com/Socapex/obs-studio/commit/8aa22a85ebcdb8449724fc17f5d79bc0a7c53ea3 together
- Reordered some of the commits
- Renamed some of the commits to be more consistent to what they do
- Fixed some whitespace alignment issues

You should open up each commit I did to try to understand what I changed and why, and then compare it to your current commits here.  It should give you a good example of the sort of stuff that I'd like to see.

Let me know if the changes are okay with you, then I'll merge them.

**Comment by Socapex** [comment]
Evrything is perfect, the new reorder method is really slick, though a bit confusing for me (I don't think I'd ever come up with a solution like that). I will close the PR once the branch is merged.

**Pull request closed without merging**
