### PR TITLE
libobs: Fix Y800 cap devices rendering as red

### PR DESCRIPTION
**Pull request by thatjpk**
See mantis ticket [0000632](https://obsproject.com/mantis/view.php?id=632).

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by RytoEX** [comment]
The commit message should be in 50/72 format (see [here](http://chris.beams.io/posts/git-commit/) for details).  The commit title should be formatted like this:
"\<component\>: [Fix/Add/Remove/\<verb\>] \<issue here\>"

**Comment by thatjpk** [comment]
@RytoEX Oops, sorry.  I've amended it.

**Comment by RytoEX** [comment]
I didn't notice that this was OpenGL only.  Jim might ask for it to be fixed in D3D11 as well before merging.

**Comment by thatjpk** [comment]
Yeah, see the mantis ticket.  I asked about that but didn't get any feedback on it.

**Comment by RytoEX** [comment]
I read the Mantis ticket.  Alas, I don't have any capture devices to test with, and that's outside my knowledge anyway.

**Comment by thatjpk** [comment]
Right on, no worries :)

**Comment by jp9000** [comment]
Your fix did not take in to account D3D11.  Additioanlly, D3D11 does not provide an L8 texture format, so such a fix via the graphics libraries wouldn't work.

It's better to just convert Y800 to RGBX instead.

**Comment by thatjpk** [comment]
@jp9000 Right on, thanks for the better fix!  FWIW I mentioned the stuff about D3D in the mantis ticket, asked for feedback, but didn't get any.  Is there a better place to do that?

**Comment by jp9000** [comment]
Ah, my apologies on that then.  Probably should have just made it an important note directly on the pull request itself.

**Comment by thatjpk** [comment]
Ah, okay.  Duly noted.  Thanks again!

**Comment by RytoEX** [comment]
@jp9000 You said it's better to convert Y800 to RGBX instead, but I noticed that the code uses "VIDEO_FORMAT_BGRX".  I did look into the code that backs that a bit and found that there is no "VIDEO_FORMAT_RGBX".  In this instance, does the RGB order not matter (RGB vs. BGR), or is this just a naming convention rather than a specific order of color values?

**Comment by jp9000** [comment]
I just used the wrong name for the commit.  There is no RGBX in terms of texture format, only RGBA, BGRA, and BGRX.

**Comment by RytoEX** [comment]
@jp9000 
Ah, okay then.  Just figured I'd ask now in case it would cause issues later.  Thanks for explaining!

**Pull request closed without merging**
