### PR TITLE
UI: Add Single/Double click options to Multiview

### PR DESCRIPTION
**Pull request by admshao**
The click to select scenes follows the same rules
as the main UI. The double click respects the option
under Settings -> General -> Studio -> Transition
to scene when Double Clicked.

### CODE REVIEW

**Comment by SuslikV** [comment]
The window size and multi-view scene index is not robust comparison. The window size not necessary has same size as drawing area. I have 5:4 display and my window previews alsways has black bars on the sides (I need manually to adjust window side). If I change the canvas size - the Multiview reflects this changes but mouse clicks by this commit - not.

I think, you need to release _OBSSource_ sources after use. I get memory leaks and crashes in w32-pthreads.dll in case of Studio Mode (_Scene Duplication_ checked), at least one Multiview transition (by double click) and OBS Studio close (by [x] button at the top right corner of the window).

**Comment by admshao** [comment]
I'll double check the clink area.

About the memory leaks its quite possible. Right now my obs is crashing on exit due to decklink plugin and i'll not load that plugin and test again. Thx for the report.

**Comment by admshao** [comment]
Fixed the clicking area.. You don't need to resize the window anymore. It will automatically only counts clicks inside sources areas.

About the need to release OBSSource and memory leaks. I'm still investigating. I get the same erros triggered if double clicking in the main UI scene in studio mode to a image source only scene.

**Comment by admshao** [comment]
I'll reopen this alter after finding a proper solution

**Comment by SuslikV** [comment]
Oh, I see.

I'd made a PR https://github.com/jp9000/obs-studio/pull/1116 that should fix the crash that were in the code itself.

**Pull request closed without merging**
