### PR TITLE
Fix YouTube name capitalization

### PR DESCRIPTION
**Pull request by FletchTech90**
I saw it in the program, couldn't help but come here and fix it.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by jp9000** [comment]
You need to make sure to prefix the commit header with the module you're modifying, like "rtmp-services: Fix YouTube name capitalization".  I'll go ahead and fix that and merge.

**Comment by FletchTech90** [comment]
Alright, sorry about that. It's my first time committing to the project.

**Comment by dodgepong** [comment]
No worries! Thanks for the contribution.

**Comment by FletchTech90** [comment]
Of course. Thanks, Ben!

**Pull request closed without merging**
