### PR TITLE
Add new Beam.pro ingests

### PR DESCRIPTION
**Pull request by JamyDev**
Hey!

We at @WatchBeam recently added a good amount of new ingests to our platform. So here's a PR to add those to OBS Studio!

\- JamyDev

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by Gol-D-Ace** [comment]
Hi. Please make sure to also increase the version numbers in package.json .
Thank you

**Comment by JamyDev** [comment]
Sure, let me do that real quick

**Comment by JamyDev** [comment]
@Gol-D-Ace I'm assuming I increase both the versions?

**Comment by Gol-D-Ace** [comment]
Yep

**Comment by JamyDev** [comment]
Cool beans! Pushed.

**Comment by Gol-D-Ace** [comment]
Could you squash the commits?

**Comment by Gol-D-Ace** [comment]
Also the commit title should be formatted like this
rtmp-services: Add new Beam.pro ingests

**Comment by JamyDev** [comment]
Done!

**Comment by Gol-D-Ace** [comment]
Not sure when they will go live.
I will let @jp9000 know about this.

**Comment by JamyDev** [comment]
Thanks, just comment in here if/when you have an estimate :)

**Comment by Gol-D-Ace** [comment]
Giving estimates is hard.
It will just happen ;)
Just look at the current version number *cough*
https://obsproject.com/obs2_update/rtmp-services/package.json

**Comment by JamyDev** [comment]
Eesh :P Well I did my part of the process ;)

**Comment by MattJustMatt** [comment]
@jp9000 @Gol-D-Ace Hey guys! Totally get that ETAs are hard here. Did want to check in and see if we could get anything on this front. We'd love to promote these new ingests but since OBS is one of our most commonly used capture tools, we'd love to get this out in-tandem. 

Thanks!

**Comment by Gol-D-Ace** [comment]
Update should be out @MattJustMatt & @JamyDev 
Thank @jp9000

**Pull request merged**
