### PR TITLE
Monitor the size of the current recording and remaining disk space.

### PR DESCRIPTION
**Pull request by adray**
The api changes are separated into another pull request
https://github.com/jp9000/obs-studio/pull/373

The mantis issue:
https://obsproject.com/mantis/view.php?id=105

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by ubuntuaddicted** [comment]
WOW, this is awesome! I'm always checking my home partition in linux because it's only 30GB and I locally store 1080p so I'm always worried about running out of space

**Comment by kc5nra** [comment]
This PR pulled in all the changes (including API).  Probably better to just issue 1 PR with two commits

**Comment by jp9000** [comment]
ok to test

**Comment by jp9000** [comment]
1.) If you're going to add a new platform-independent API function, don't just implement a single platform.  At the very least add usable stubs for other platforms, functions that will compile and be usable but just return 0 or something.  As it is, anything using these API functions will fail to compile.
2.) You should probably use #ifdefs to prevent the code from being used on operating systems other than windows until someone else fills in the blanks.
3.) = {0}; instead of = { 0 };
4.) You tried to make it reference #373, but you ended up just including all of #373's code in the single commit you have here, which just conflicts with #373, not extends it
5.) Commits should be considered annotation to code.  You do two things in a single commit, but your commit message implies you do one thing.  Is it adding API to query remaining disk space, or is it adding API to query the size of a file?  You could hypothetically make a commit that does both and give it an appropriate message, but ideally if you are able to split a commit because of two or more different segments of compilable code.
6.) Due to the monolithic nature of the repo, commit message should be prefixed with the module name to signify where changes are occurring, example "libobs: Add API to query disk space information", unless they have to modify multiple modules.
7.) Commit messages need to be concise and to the point, in the 50/72 format: See http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by adray** [comment]
Thanks for the detailed response, I have addressed most of those issues, still not quite ready.

Afraid it will have to be stubs for the other platforms for now.

**Comment by jp9000** [comment]
Ah excellent, thank you!  The function stubs are no problem, we'll fill in the blanks.  I really appreciate it.  Will give it a look.

**Comment by adray** [comment]
@reboot I moved the disk usage to its own timer. As for the file size, I had overlooked a function which already exists for this, which does it by similar means. Though whether it is safe to assume it will work if the file is currently open for writing, I have not been able to find a definite answer.

**Comment by kc5nra** [comment]
jenkins test this please

**Comment by kc5nra** [comment]
jenkins test this please

**Comment by kc5nra** [comment]
jenkins test this please

**Comment by kc5nra** [comment]
jenkins test this please

**Comment by kc5nra** [comment]
jenkins test this please

**Comment by jp9000** [comment]
jenkins test this

**Comment by jp9000** [comment]
ok to test

**Comment by Streusel** [comment]
@jp9000 close? pull? status?

**Comment by jp9000** [comment]
I left this open because again there were changes that had to be made, but I got majorly distracted by recent patches (and let it slide way too long).  Now that 0.11.0 is completed I'll have time to look at the pull request again.

**Comment by timelf123** [comment]
Thanks for all the recent patches @jp9000 - the new 0.11.0 is looking good!

**Comment by ovr** [comment]
@jp9000 ping, any news?

**Comment by jp9000** [comment]
I haven't closed it because I intend to add it, but It's been on the back-burner.  Still is for a bit.

It requires support for all three operating systems, and doesn't quite function the way I want, so it's still considered incomplete.

**Comment by jp9000** [comment]
I should probably just make this a mantis issue and close this particular pull request, because I don't intend on adding this specific code.  I still have this on a branch on my windows computer.  I'll have to check and make sure it's still there though.  If it is, then I'll close the pull request and make it an item on the bug tracker for 0.13.0 or 0.14.0.

**Comment by jp9000** [comment]
I finally took some time for the non-windows equivalent version of your function, and cleaned things up a bit (3e6db99 and e354a43), tested and verified as functional.  This solves the issue of API functions for getting free space and file size, but for now there hasn't been a decision on how to put it in to the UI yet, primarily because there's no room on the status bar.  The status bar is currently too cluttered, and I feel like a lot of the main window really needs a redesign.  For the time being the actual issue of displaying the file size and free space will remain unsolved until UI issues have been worked out.

For now I'm going to close this PR and leaving the issue on the bug tracker, here:  https://obsproject.com/mantis/view.php?id=105

**Pull request closed without merging**
