### PR TITLE
obs-text: Let file content update frequency configurable

### PR DESCRIPTION
**Pull request by copyliu**
It will help some people who want to put a very frequently updated files

### CODE REVIEW

**Comment by jp9000** [comment]
I would prefer not to have to update at more than a 1 second frequency if possible.

**Comment by robske110** [comment]
Just a `vote` for this feature, because it opens many possibilities.

**Comment by dodgepong** [comment]
Can you explain those use cases? It's possible there is a better way to accomplish what you are trying to do rather than via the text source.

**Comment by copyliu** [comment]
I think users can use scripts if they need more frequency updated text after OBS 21.0

**Pull request closed without merging**
