### PR TITLE
Update services.json

### PR DESCRIPTION
**Pull request by vaughnsoft**
Updated video ingest servers for Vaughn Live and set it as a common service since most of our users use OBS. Also split Breakers.TV into its own since it is possibly becoming its own entity soon.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by Nightfirecat** [comment]
FYI, you need to update the version and re-format your commit message; see #770 as an example.

**Comment by vaughnsoft** [comment]
I don't understand what you mean by update the version.

**Comment by Gol-D-Ace** [comment]
https://github.com/jp9000/obs-studio/blob/master/plugins/rtmp-services/data/package.json

L3 & L7

**Comment by derrod** [comment]
Also the way profile should be set is via the `profile` property. I would alsp argue that marking the service as "common" is debatable.

**Comment by vaughnsoft** [comment]
I'm not updating package.json, just services.json. As for my service being listed as common, I have higher traffic than hitbox and beam, and quite a few other services, so why not?

**Comment by Gol-D-Ace** [comment]
The package.json describes the version of the services.json
You're updating the services.json which will require increasing the version in the package.json

**Comment by vaughnsoft** [comment]
Ah, gotcha. I wasn't aware of that.

**Comment by vaughnsoft** [comment]
Closed? I'm confused.

**Comment by Gol-D-Ace** [comment]
jp9000 closed this in ea0f47e 4 minutes ago
The important part is "in ea0f47e".

**Comment by vaughnsoft** [comment]
Ah okay. I see only part of my changes were committed. profile=baseline was removed and so was common: true.

**Comment by jp9000** [comment]
For now, I did remove the baseline profile.  There wasn't a valid technical reason to justify that.  Web browsers are more than capable of handling main/high profiles, and we've never had an issues in that regard.  If you're using flash for playback, then that may be a different story, but even flash was also capable of main/high profiles.  (Flash also has terrible decoding performance, if you're using it you should consider HTML5 ASAP)

**Comment by vaughnsoft** [comment]
The reason for baseline profile is for WebRTC playback. Unless it's set to baseline profile the playback in the browser does not render correctly. We are starting WebRTC testing for certain streams on our sites in the coming weeks and it is required the baseline profile is used. 

Also, not sure why our service isn't allowed to be listed as common. We get more traffic than a few of the sites listed as common.

**Comment by jp9000** [comment]
Let me preface first:  Just so you know I don't mean to cause you problems.  Nor am I purposely trying to be stubborn or anything.  When I removed that from your mandatory encoder settings, it was because there is almost assuredly a misunderstanding, because no streaming service would ever implement a mandatory low-definition profile on their streamers.

First, I'll need some sort of citation.  I cannot find any evidence that WebRTC requires the baseline H264 profile.  If it actually did and I were in your position, I'd immediately say "right, this is garbage", toss it in the bin, and start looking for something else, because the baseline H264 profile is an absolutely ridiculous thing to have to use.  It's meant almost specifically for video conferencing and mobile programs.  It's basically a low-definition profile.  Then main is meant for standard definition, and high is meant for high definition.

After searching and scouring the net, the closest I see is an old WebRTC implementation memo from many many years ago, which may have been the root cause of this confusion:
https://tools.ietf.org/id/draft-burman-rtcweb-h264-proposal-01.html

In the introduction section, it says:  "The core of the proposal is that H.264 Constrained Baseline Profile Level 1.2 MUST be supported as Mandatory To Implement video codec." However, this is referring to implementation.  When it says "MUST", and "Mandatory", it's not saying that baseline "must be used", it's saying that baseline "must be implemented", and it's meaning minimum.  And case in point, the very next line says: "To enable higher quality for devices capable of it, support for H.264 Constrained High Profile Level 1.3, extended to support 720p resolution at 30 Hz framerate is RECOMMENDED."

Do not make the mistake of misunderstanding this document.  This document is meant for client applications (i.e. web browsers) that implement WebRTC.  Not web sites.

Web browsers fully support main/high profiles, they use FFmpeg pretty extensively for both decoding and profiles, and it'd be silly if they only implemented baseline.  If you feel I am incorrect, I would humbly ask that you show me a proper citation for this, and not just base it upon circumstantial evidence just because you're seeing some playback issue.  Playback issues can be caused by any number of things.  I see your other comments on the OBS1 repository now, and you stated that it simply didn't look smooth with WebRTC.  But if WebRTC doesn't support it, why would it even be playing it back in the first place?

I do not want to see people needlessly completely gimp their encoder settings due to a potential misunderstanding, or assumption based upon false premise.  There are too many misconceptions and misunderstandings about encoder settings out there, and it just causes me pain to see it.

**Comment by vaughnsoft** [comment]
No I totally get it but we're moving into new territory with WebRTC and I'd like OBS Studio to work out of the box for our users as far as WebRTC compatibility. I know you guys are working on that already, but in the meantime this is the solution we came up with for those that don't want to use the web based WebRTC broadcaster. It's been a week since I discovered only baseline, regardless of encoder, will work with WebRTC and h264 playback. Now granted this could be some sort of SDP issue within Wowza causing this, but I haven't had time to test WebRTC on other video server software to verify. Sounds like the best solution for the time being is to give my users instructions on how to set the baseline profile in OBS Studio rather than it automatically be set. 

I appreciate the response!

Also, about Vaughn Live being listed under common? 😃

**Comment by jp9000** [comment]
Well I suppose my point was I think the WebRTC issue can't be an issue with with the encoder profile setting.  I really don't think that's the problem.  I definitely think you should absolutely confirm 100% before making that assumption and using a profile that's usually only used for video conferencing.  It'll negatively impact quality, so it's not something you should do lightly.  You should not be telling your users or forcing your users to use baseline.  It's just madness, this isn't something that should be accepted at all.  I see no data suggesting that suggests that proper profiles can't be supported.  You shouldn't be accepting it either, you can't accept it.  You should not do this.  With the utmost respect, it's absolutely crazy, you have to investigate in find out the cause of the issue, it feels too much like it's being made as an assumption; don't accept circumstantial evidence in this case.

As for the common thing, I take it on a case-by-case basis, I'm going to try to remove the checkbox in a patch or two, it's kind of stupid and can be inconsistent, I admit.  I did consider it when you made this pull request, but email me or PM me some time about it if you have time and I'll talk about why.

**Pull request closed without merging**
