### PR TITLE
obs-ffmpeg: Improve nvenc detection

### PR DESCRIPTION
**Pull request by OsirisNL**

### CODE REVIEW

**Comment by RytoEX** [comment]
Neat!  I'd tried something very similar to this, but it still detected that NVENC was supported on a system that had no Nvidia cards.  Does this log an FFmpeg/NVENC error when NVENC is not supported, or does it omit any logging in that case?

**Comment by OsirisNL** [comment]
Nah, it doesn't log anything if it isn't supported.
I tested it on a VM with no NVIDIA GPU and just copied NvEncodeApi64.dll to System32 which was enough to make 20.1.3 think NVENC was supported. Using the version with this fix applied on the VM results in OBS no longer thinking NVENC is supported, on my PC with an NVIDIA GPU it still reports as supported.

**Comment by SuslikV** [comment]
Shouldn't we free the context if succseed? `avcodec_free_context(&context)`

**Comment by jp9000** [comment]
I fixed this a bit to prevent possible memory leaks.  Merging shortly, you'll see "closed in [commit]".

**Comment by jp9000** [comment]
Additionally, just wanted to note that this check takes approximately 500ms, increasing load time by a notable margin.  We may want to consider a more proper way to perform NVENC detection in the future rather than actually initializing an encoder context (see OBS1's code, or the crucible NVENC code on forge's repository by Palana).  However, for the time being, it's a sufficient workaround under time constraints.

**Comment by RytoEX** [comment]
I was doing some research into this a few weeks ago.  FFmpeg has functions for checking NVENC support, but they're static C functions, so we can't call them.

We could try making the calls directly against the NVENC API to check the card's capabilities and NVENC support, though that may be a bit nightmarish.

**Pull request closed without merging**
