### PR TITLE
UI/media-io/decklink/obs-filters: Multichannel audio

### PR DESCRIPTION
**Pull request by pkviet**
**Recording and Streaming multichannel audio sources (surround sound).**

**Compatible streaming services:** Twitch, Mixer rtmp (not ftl), smashcast, FB 360 live
**Compatible protocols:** rtmp / mpeg-ts tcp udp (others untested).
**Servers tested:** wowza, nginx-rtmp
**html5 players tested with live surround:**
 videojs, bitmovin, mediaelement, viblast (hls & dash), hls.js
**Compatible containers:** mkv mp4 ts flv (others untested).
**Compatible codecs:** ffmpeg aac, libfdk_aac, core audio aac , opus, vorbis, pcm (others untested).
**Decklink:** change channels order for 5.1 7.1 to comply with ffmpeg on win.
**Audio filters:** extended to support multichannel.
**Monitoring:** multichannel enabled for win, mac, linux (pulse-audio).
**VST:** stereo plugins keep in general only the first two channels.
              multichannel plugins should work (e.g. mcfx does).
**OS:** compatible with win, macOS, linux (alsa, pulse-audio).
**Misc:** Higher audio bitrates unlocked to accomodate higher number of channels.
All outputs are working with surround (simple, advanced, standard record, ffmpeg record) except FTL which does not support surround.

(Reopening of [https://github.com/jp9000/obs-studio/pull/939] ; 
see comments there for history of PR)

### CODE REVIEW

**Comment by pkviet** [comment]
Update:

- CoreAudio aac channel mapping corrected to put in line with FFmpeg  / wav

- libfdk_aac small fixes to make compatible with multichannel

**Comment by pkviet** [comment]
**Update:**

- compatible with Mixer rtmp service (not Mixer FTL which has a stereo player)

**Comment by pkviet** [comment]
**Update:**

- tested with smashcast.tv, works fine with surround sound.

**Comment by pkviet** [comment]
**To do:**

- with addition of pulse audio monitoring, needs to update linux code  (requires minor additions to code, not difficult)
- 16 channels setups work for recording to mkv with opus but not for streaming in mpeg-ts with opus (ffmpeg does not support opus in mpegts for more than 8 channels; I have submitted a patch to ffmpeg to remedy that)
- decklink channel swapping was fixed for windows but there is still swapping on mac due to different default channels setups so the swapping code must be OS customized

**Comment by pkviet** [comment]
Update:

- pulse-audio monitoring enabled for multichannel
- decklink: there is a channel swap on windows and linux, but not on macOs; issue fixed.

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by pkviet** [comment]
**Update 10/05/2017:**

- Full support in rtmp of up to 16 channels in aac.

- Requires a patched ffmpeg enabling aac encode beyong 7.1 (branch aacdev of my FFmpeg fork); the patch is with ffmpeg main aac maintainer who started the work on enabling PCE (program config element) with aac encoder.
(For libopus + mpeg-ts support beyond 7.1, another ffmpeg patch is necessary; I've submitted to ffmpeg dev for review. For recording to mkv, no patch is necessary to record up to 255 channels, only the mapping_family=255 argument).

**Comment by pkviet** [comment]
**Update:**
* binaries are available for testing purposes in the repo of [my fork](https://github.com/pkviet/obs-studio).  
* I have used them without issues in prod though.

**Comment by jp9000** [comment]
I've gone through and reviewed the PR -- and you checked just about every edge case.  Great job.  However, there is one thing that I personally disagree with for now -- adding 16 channel support.  I know that for your specific use case you needed this, but for now I want to avoid going up to 16 channels unless necessary.  It's just such a niche use case that's so unlikely to be used that I can't justify changing the API for it right now.  I'm going to remove the 16 channel support, clean up the code a bit, and then merge.  Perhaps later when I've evaluated it a bit more we can up it to 16 channel support, but for now I just prefer to stick to 2.1/4.0/5.1/7.1 support.

I'm also changing the way it warns users when selecting 5.1/7.1/etc, instead of having that checkbox that the user has to check, the items will be there, and when the user selects those items, they will get a warning when they try to select surround sound items, similar to when you select lossless when you're changing the recording quality in the output section -- I feel like that's a little bit better of a user experience.  (Just so people know I was the one who originally suggested the checkbox, but I now realize that it's not as ideal as a popup when trying to select the item, so that one was on my, not pkviet).

Additionally, the warning in the audio section has been changed to an orange warning label, and is a separate label from the red one used to tell the user that they need to restart.  It makes it more clear to the user that they need to restart the program, that way the restart warning doesn't get lost in a sea of red text.

Other than those things, this is great work.  I apologize it took me so long to get around to this -- I've been purposely delaying reviewing some of the bigger PRs due to time constraints before.  You did a great job in testing/verifying where they worked and giving a full report on what it works with and what it doesn't work with, and accounting for just about every edge case -- you even made sure that the AAC bitrates increased, and you even checked to see what encoders it worked with and what encoders it didn't work with.  You were very thorough, definitely a quintessential pull request if I've seen one.

I will be merging this soon with some minor changes -- you'll see "closed in [commit hash]".

**Comment by pkviet** [comment]
Thanks a lot again.
I agree with your assessment of 16.0 ; it is indeed very very fringe case. I'll keep it in a separate fork.
If you're OK with it, I would like to work on a wiki page on surround sound / multichannel, integration in a DAW, decklink etc ...

**Comment by jp9000** [comment]
Feel free if there's something that requires explanation.  It should work pretty much automatically though.

**Pull request closed without merging**
