### PR TITLE
Add the "flip horizontally" option to the Video Capture Device

### PR DESCRIPTION
**Pull request by EpicCoder**

### CODE REVIEW

**Comment by Gol-D-Ace** [comment]
Why?
The transform function / menu is already covering this.

**Comment by EpicCoder** [comment]
Yes but why is there a flip vertically option in the video capture device properties? And i think it is not bad to add a flip horizontally option because it is easier to see if one or both options are enabled or not as the transform function

**Comment by beeanyew** [comment]
The flip vertical option is there because some (often virtual) capture devices that output RGB do so the incorrect way, and need to be flipped to be displayed the right way around. There are however no capture devices that output horizontally flipped video for any reason.

**Comment by EpicCoder** [comment]
With the "flip horizontally" there is no issue when manual resize the transform

https://obsproject.com/forum/threads/horizontal-cam-flip-undone-by-manual-resizing.54156/

**Comment by jp9000** [comment]
The bug you're seeing with the resize in that case you linked has to do with the transform.  The scene item transform process is what needs to be fixed.

**Pull request closed without merging**
