### PR TITLE
Make OBS compile + run on FreeBSD 10.X and later

### PR DESCRIPTION
**Pull request by kmoore134**
Most of the changes involve some of the Linux assumptions and
adding the various #ifdef __FreeBSD__ lines for them.

Additionally, some of the linux-v4l plugin was adjusted to support
the older version of v4l compat in FreeBSD and probing for the /dev/video* devices.

### CODE REVIEW

**Comment by ONSBalder** [comment]
Can one of the admins verify this patch?

**Comment by kmoore134** [comment]
On 05/01/2015 16:10, ONSBalder wrote:
>
> Can one of the admins verify this patch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jp9000/obs-studio/pull/421#issuecomment-98222176>.
>

I'm going to be committing a version with these patches to the FreeBSD
ports tree later today, so if somebody needs to test it out on a FreeBSD
box, that would probably be the easiest way.

The port is already in our fork here:

https://github.com/pcbsd/freebsd-ports/tree/master/multimedia/obs-studio/

-- 
Kris Moore
PC-BSD Software / iXsystems
Enterprise Storage & Servers Driven By Open Source

**Comment by jp9000** [comment]
ok to test

**Comment by fryshorts** [comment]
Patches split up and resubmitted with other fixes here: #424

**Pull request closed without merging**
